default: &default
  logo: "new/logo_color.png"
  site_name: 'Canvas Theme'
  site_slogan: "Theming"
  hero1: 'hero1.jpg'

canvas:
  site_name: 'Canvas'
  site_code: 'canvas'
  <<: *default

eyeofhorus: &horus
  <<: *default
  site_name: "Eye of Horus"
  site_code: 'eyeofhoruscosmetics'
  site_slogan: 'Awaken the Goddess Within'
  page_title: "Eye of Horus Stockists | Mascara, Eyeshadow, Eyeline, Makeup Specialists"
  address_street: '17 Lawson Street'
  address_city: 'Byron Bay'
  address_postcode: '2481'
  address_state: 'NSW'
  address_country: 'Australia'
  phone_one: '(02) 6685 XXX'
  phone_two: '(02) 6685 XXX'
  email: 'info@eyeofhoruscosmetics.com'
  domain: 'stockists.eyeofhoruscosmetics.com'
  shop: 'http://eyeofhoruscosmetics.com'
  logo: 'http://cdn.shopify.com/s/files/1/0717/7955/t/2/assets/logo.png?1311'
  tag_manager: 'GTM-KVHWWC'
  copyright: 'RA Cosmetics Pty Ltd trading as Eye of Horus ABN: 40 146 108 107'
  description: "<p>Eye of Horus illuminating essential range of Goddess eye makeup is based on ancient Egyptian formulas and ingredients, including the revered Moringa Oil claimed by the gods for its beautifying and regenerating powers.</p>
<p>Eye of Horus hypnotic and high performance products Awakens the Goddess Within you, by delivering cosmetic that are:</p>
<ul><li>Lengthening</li><li>Volumising</li><li>Smudgeproof</li><li>Non clumping</li><li>Non sensitising.</li></ul>
<p>Representing regeneration, health and protection, the ancient Egyptian Symbol of the Eye of Horus ensures healing, wisdom and prosperity to its bearer. The ancients used the most precious waxes and oils in their iconic eye makeup, including:</p>
<p>Beeswax, Ricebran Wax, Canauba, Candellia, and Jojoba waxes and Almond , Moringa, and Sesame oils.</p>"

childrenofthetribe:
  <<: *default
  site_name: "Children of the Tribe"
  site_code: 'childrenofthetribe'
  site_slogan: 'Children of the Tribe'
  page_title: "Children of the Tribe"
  address_street: '17 Lawson Street'
  address_city: 'Byron Bay'
  address_postcode: '2481'
  address_state: 'NSW'
  address_country: 'Australia'
  phone_one: '(02) 6685 XXX'
  phone_two: '(02) 6685 XXX'
  email: 'info@childrenofthetribe.com'
  domain: 'stockists.childrenofthetribe.com'
  tag_manager: 'GTM-XXX'

stockists:
  <<: *horus
