# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
Stockist.create(name: 'Eye of Horus HQ', city: 'Byron Bay', state: 'New South Wales', postcode: '2481', country: 'Australia', street_address: '17 Lawson Street')
Stockist.create(name:'Store Name', country:'Country',postcode:'Postal / Zip Code',street_address:'Address')
Stockist.create(name:'Eye of Horus Headquarters', country:'Australia',postcode:'3228',street_address:'1-44 Puebla Street')
Stockist.create(name:'Ara Beauty and Day Spa', country:'Australia',postcode:'2011',street_address:'Diamant Hotel, Suite 8.10, 14 Kingscross Road')
Stockist.create(name:'Actual Wellness &amp; Beauty', country:'Australia',postcode:'3038',street_address:'Sibyl Court')
Stockist.create(name:'Allure for Beauty', country:'Australia',postcode:'3161',street_address:'213 Balaclava Road')
Stockist.create(name:'Allure Skin &amp; Body', country:'Australia',postcode:'3144',street_address:'251 Glenferrie Road')
Stockist.create(name:'Areti Skin Therapy', country:'Australia',postcode:'3149',street_address:'Mt Waverley')
Stockist.create(name:'Aura Beauty', country:'Australia',postcode:'3585',street_address:'Shop 10 Safeway Arcade')
Stockist.create(name:'Bayside Beauty Lounge', country:'Australia',postcode:'3931',street_address:'Shop5/216 Main Street')
Stockist.create(name:'Beauty Delphine ', country:'Australia',postcode:'3095',street_address:'43 Floriston Grove')
Stockist.create(name:'The Beauty Studio', country:'Australia',postcode:'3232',street_address:'146a Mountjoy Parade (off Brownes Lane)')
Stockist.create(name:'Beauty Works', country:'Australia',postcode:'3616',street_address:'6 Flanagan Drive ')
Stockist.create(name:'Body &amp; Soul Day Spa Beauty Therapy', country:'Australia',postcode:'3193',street_address:'4 North Concourse Road')
Stockist.create(name:'Body &amp; Soul Day Spa Beauty Therapy', country:'Australia',postcode:'3186',street_address:'246 Bay Street')
Stockist.create(name:'Body Glow Beauty Therapy ', country:'Australia',postcode:'3152',street_address:'L 1, 452 Burwood Highway')
Stockist.create(name:'Body Works Organic Spa', country:'Australia',postcode:'3677',street_address:'Shop 3, 103 Murphy Street')
Stockist.create(name:'Calm Beauty Therapy', country:'Australia',postcode:'3806',street_address:'4 Riverglen Road')
Stockist.create(name:'Calma Medispa Retreat', country:'Australia',postcode:'3143',street_address:'1100 High Street ')
Stockist.create(name:'Clay Skin &amp; Body Salon Spa', country:'Australia',postcode:'3016',street_address:'97 Douglas Parade')
Stockist.create(name:'Clover Beauty Skin &amp; Body ', country:'Australia',postcode:'3143',street_address:'1 Kings Way')
Stockist.create(name:'Coburg Health Shop', country:'Australia',postcode:'3058',street_address:'5/, Shop 5, 461-463 Sydney Road')
Stockist.create(name:'Dermal Aesthetics Laser Clinic', country:'Australia',postcode:'3931',street_address:'The Bays Hospital, Level 1/ 262 Main Street')
Stockist.create(name:'Dermal Resolution', country:'Australia',postcode:'3807',street_address:'56 Oneil Road')
Stockist.create(name:'Elita Cosmetic Medicine', country:'Australia',postcode:'3046',street_address:'4 Post Office Place ')
Stockist.create(name:'Eyelash Inez', country:'Australia',postcode:'3082',street_address:'43 Streeton Circuit')
Stockist.create(name:'Feeling Smooth', country:'Australia',postcode:'3207',street_address:'120 Bridge Street ')
Stockist.create(name:'Fiona Fairley', country:'Australia',postcode:'3631',street_address:'615 Archer Road')
Stockist.create(name:'Flavour Beauty Therapists', country:'Australia',postcode:'3102',street_address:'666 High Street ')
Stockist.create(name:'Fringe Benefits Organics', country:'Australia',postcode:'3194',street_address:'30 Mountview Avenue')
Stockist.create(name:'Giota Hairdresser', country:'Australia',postcode:'3081',street_address:'Bellfield/Ivanhoe area ')
Stockist.create(name:'Go Vita Doncaster', country:'Australia',postcode:'3108',street_address:'Shop G200 Westfield Shopping Centre, 619 Doncaster Road')
Stockist.create(name:'Go Vita Forest Hill', country:'Australia',postcode:'3131',street_address:'Shop 13 Market Place, Forest Hill Chase, 270 Canterbury Road')
Stockist.create(name:'777 Whitfords City Pharmacy', country:'Australia',postcode:'6025',street_address:'Shop 42, Westfield Whitford City, Whitfords Avenue ')
Stockist.create(name:'Aesthetica', country:'Australia',postcode:'4161',street_address:'Shop 8, 377 Cavendish Road')
Stockist.create(name:'AFS Friendly Care Pharmacy', country:'Australia',postcode:'4740',street_address:'4 Ways Plaza 135-137 Nebo Road')
Stockist.create(name:'Alfred Hospital', country:'Australia',postcode:'3004',street_address:'55 Commercial Road ')
Stockist.create(name:'Amcal Max Doncaster ( Chandra Pharmacy )', country:'Australia',postcode:'3109',street_address:'274-276 Blackburn Road')
Stockist.create(name:' Wendouree Village Pharmacy ', country:'Australia',postcode:'3355',street_address:'Shop 73  Stocklands Wendouree Gillies Street, Wendouree Shopping Centre')
Stockist.create(name:' Mundaring Pharmacy ', country:'Australia',postcode:'6073',street_address:'Shop 4/ 5 Nichol Street')
Stockist.create(name:'Inverell Amcal Pharmacy ', country:'Australia',postcode:'2360',street_address:'132- 134 Byron Street')
Stockist.create(name:'Armidale Pharmacy ', country:'Australia',postcode:'2350',street_address:'114 Dangar Street')
Stockist.create(name:'Aroma Beauty Therapy Clinic', country:'Australia',postcode:'4216',street_address:'9/131 Morala Avenue')
Stockist.create(name:'Avenues Hair', country:'Australia',postcode:'4817',street_address:'The Avenues Shopping Centre Corner Kern Brothers Drive &amp; Burnda Street')
Stockist.create(name:'AWB Holdings ', country:'Australia',postcode:'4223',street_address:'9 Traders Way')
Stockist.create(name:'Chemplus Balhannah ', country:'Australia',postcode:'4721',street_address:'Shop 3/84 Main Road')
Stockist.create(name:'Barracks Pharmacy', country:'Australia',postcode:'4000',street_address:'61 Petrie Terrace (top of Caxton Street)')
Stockist.create(name:'Bayswater North Pharmacy ', country:'Australia',postcode:'3153',street_address:' 17-39 Canterbury Road')
Stockist.create(name:'Beauty Bizz', country:'Australia',postcode:'6255',street_address:'Shp2/ 84 Hampton Street')
Stockist.create(name:'Benowa Gardens Amcal Pharmacy ', country:'Australia',postcode:'4217',street_address:'Gardens Shopping Centre Corner Ashmore &amp; Benowa Road')
Stockist.create(name:'Black Rock Amcal Pharmacy', country:'Australia',postcode:'3193',street_address:'6 Bluff Road')
Stockist.create(name:'Blooms The Chemist - Miranda', country:'Australia',postcode:'2228',street_address:'Shop 2089 Westfield Miranda')
Stockist.create(name:'Blooms The Chemist - Shellharbour ', country:'Australia',postcode:'2529',street_address:'Shop 11-12 Stockland Shopping Centre')
Stockist.create(name:'Blooms The Chemist - Belmont Central ', country:'Australia',postcode:'2280',street_address:'Shop 24, Belmont Central Shopping Centre, Singleton Street')
Stockist.create(name:'Bode Hair Lounge', country:'Australia',postcode:'5061',street_address:'2/384 Unley Road')
Stockist.create(name:'Boulder Beauty Care ', country:'Australia',postcode:'6432',street_address:'22 Burt Street')
Stockist.create(name:'Bowen Healthcare pharmacy ', country:'Australia',postcode:'4805',street_address:'16 Gregory Street')
Stockist.create(name:'Brands Pharmacy ', country:'Australia',postcode:'2480',street_address:'136 Molesworth Street')
Stockist.create(name:'Butchers Pharmacy ', country:'Australia',postcode:'3101',street_address:'101 Willsmere Road')
Stockist.create(name:'Byron Bay Plaza Amcal Pharmacy ', country:'Australia',postcode:'2481',street_address:'Shop 4B/5-6 Byron Bay Plaza North Jonson Street')
Stockist.create(name:'Amcal Pharmacy ', country:'Australia',postcode:'4157',street_address:'Capalaba Park Shopping Centre, 7-45 Redland Bay Road')
Stockist.create(name:'Care Plus Pharmacy Sydenham', country:'Australia',postcode:'3037',street_address:'523 Melton Highway')
Stockist.create(name:'Chelsea Central Soul Pattinson Pharmacy', country:'Australia',postcode:'3196',street_address:'425 Nepean Highway')
Stockist.create(name:'Chemist Works, Glendale', country:'Australia',postcode:'2285',street_address:'Shop 22, Lake Road, Stockland Drive')
Stockist.create(name:'Brighton Chemmart Pharmacy ', country:'Australia',postcode:'5048',street_address:'479 Brighton Road')
Stockist.create(name:'Chemmart Pharmacy Superstore - Geraldton', country:'Australia',postcode:'6530',street_address:'113 Marine Terrace')
Stockist.create(name:'Waikerie Chemplus Pharmacy ', country:'Australia',postcode:'5330',street_address:'1 White Street')
Stockist.create(name:'Chi Hair Skin and Body - Hallett Cove', country:'Australia',postcode:'5158',street_address:'Shop 54, Hallett Cove Shopping Centre')
Stockist.create(name:'Classic Beauty Therapy', country:'Australia',postcode:'4350',street_address:'Range Shopping Centre, James Street')
Stockist.create(name:'Clip Go the Shears', country:'Australia',postcode:'5360',street_address:'13 Murray Street')
Stockist.create(name:'Creelmans Pharmacy', country:'Australia',postcode:'3000',street_address:'Shop 20 Target City Centre 222 Bourke Street')
Stockist.create(name:'Amcal Max Dalby Pharmacy', country:'Australia',postcode:'4405',street_address:'Shop 22, Dalby Shopping World Cunningham Street')
Stockist.create(name:'Day Night Chemist Crows Nest', country:'Australia',postcode:'2065',street_address:'9 Willoughby Road')
Stockist.create(name:'Direct Chemist Outlet Mt Waverley ', country:'Australia',postcode:'3149',street_address:' 33 Hamilton Place')
Stockist.create(name:'Debras Beauty Shoppe', country:'Australia',postcode:'5068',street_address:'365 Kensington Road ')
Stockist.create(name:'Direct Chemist Outlet - Glenroy', country:'Australia',postcode:'3046',street_address:'785 Pascoe Vale Road ')
Stockist.create(name:'Discount Pharmacy Australia Ripponlea', country:'Australia',postcode:'3185',street_address:'93 Glen Eira Rd')
Stockist.create(name:'Dupuys Pharmacy', country:'Australia',postcode:'4740',street_address:'12-14 Grandview Drive')
Stockist.create(name:'Ebony Beauty Noosa', country:'Australia',postcode:'4566',street_address:'2, 11 Lake Weyba Drive')
Stockist.create(name:'Amcal Pharmacy - Euroa', country:'Australia',postcode:'3666',street_address:'26 Binney Street')
Stockist.create(name:'Face Bar', country:'Australia',postcode:'7310',street_address:'22 Stewart Street')
Stockist.create(name:'First Wave Hair Shoppe', country:'Australia',postcode:'4224',street_address:'474 Golden Four Drive')
Stockist.create(name:'Forest Lakes Pharmacy', country:'Australia',postcode:'6108',street_address:'Shopping Centre, Corner Forest Lakes Drive &amp; Murdoch Road')
Stockist.create(name:'Forestway Pharmacy', country:'Australia',postcode:'2086',street_address:'Shop 24 Forestway Cntr, 2-18 Forest Way')
Stockist.create(name:'Friendlies Chemists Subiaco', country:'Australia',postcode:'6008',street_address:'136-142 Rokeby Road')
Stockist.create(name:'Friendlies Chemist Leederville', country:'Australia',postcode:'6007',street_address:'143 Oxford Street')
Stockist.create(name:'Frost Pharmacy', country:'Australia',postcode:'3095',street_address:'Eltham Village Center Corner Main Road &amp; Arthur Street')
Stockist.create(name:'Fuze Hair &amp; Beauty', country:'Australia',postcode:'4305',street_address:'5a Jacaranda St ')
Stockist.create(name:'Gaia Song Natural Health', country:'Australia',postcode:'6280',street_address:'Shop 14- 16 Fig Tree Lane')
Stockist.create(name:'Chemplus Pharmacy Gawler', country:'Australia',postcode:'5118',street_address:'21 Adelaide Road')
Stockist.create(name:'Glam Nails ', country:'Australia',postcode:'4551',street_address:' Currimundi Junction, 5a, 710 Nicklin Way')
Stockist.create(name:'Go Vita Currambine', country:'Australia',postcode:'6028',street_address:'T2 Currambine Central, Cnr Marmion &amp; Shenton Avenues')
Stockist.create(name:'Go Forest Hill', country:'Australia',postcode:'3131',street_address:'Shop 13 Market Place, Forest Hill Chase, 270 Canterbury Road')
Stockist.create(name:'Go Vita Greensborough', country:'Australia',postcode:'3088',street_address:'Level 1 Shop 121A Greensborough Plaza, 25 Main Street')
Stockist.create(name:'Go Vita Greenwood', country:'Australia',postcode:'6024',street_address:'Shop 4 Greenwood Village Shopping Centre')
Stockist.create(name:'Go Vita Kalgoorlie', country:'Australia',postcode:'6430',street_address:'279 Hannan Street')
Stockist.create(name:'Go Vita Knox City ', country:'Australia',postcode:'3152',street_address:'Shop 1063 Knox City Shopping Centre, 425 Burwood Highway')
Stockist.create(name:'Go Vita Rye ', country:'Australia',postcode:'3941',street_address:'Shop 4 Safeway Complex Point Nepean Road')
Stockist.create(name:'Go Vita Southland/Willetton', country:'Australia',postcode:'6155',street_address:'Shop 31 Southlands Boulevard')
Stockist.create(name:'Go Vita Tanunda', country:'Australia',postcode:'5352',street_address:'98 Murray Street')
Stockist.create(name:'Go Vita Warrnambool', country:'Australia',postcode:'3280',street_address:'155 Fairy Street')
Stockist.create(name:'Go Vita Woodvale', country:'Australia',postcode:'6026',street_address:'Shop 11 Woodvale Boulevarde Shopping Centre, Corner of Whitfords Avenue &amp; Trappers Drive')
Stockist.create(name:'Goddess Body Treatments', country:'Australia',postcode:'3094',street_address:'13 Were Street')
Stockist.create(name:'Goldfields Fullife Pharmacy', country:'Australia',postcode:'4570',street_address:'Goldfields Plaza Monkland Street')
Stockist.create(name:'Gore &amp; Dickson Pharmacy', country:'Australia',postcode:'3207',street_address:'243-247 Bay Street')
Stockist.create(name:'Grace and Style Professional Hair &amp; Make up ', country:'Australia',postcode:'4061',street_address:'1 Kadina Street')
Stockist.create(name:'MakeUp By Rory', country:'United States',postcode:'33137',street_address:'2001 Biscayne Blvd #117/77')
Stockist.create(name:'Zenyu Skin &amp; Body', country:'Australia',postcode:'3931',street_address:'8/234 Main St, Mornington VIC 3931')
Stockist.create(name:'Woods Pharmacy Royal Childrens Hospital', country:'Australia',postcode:'3052',street_address:'50 Flemington Rd Parkville VIC 3052')
Stockist.create(name:'Williams &amp; Golby Boronia', country:'Australia',postcode:'3155',street_address:'Boronia Mall Shopping Centre 47 Dorset Square  Boronia VIC 3155')
Stockist.create(name:'Wild for Beauty', country:'Australia',postcode:'3054',street_address:'795 Rathdowne Street')
Stockist.create(name:'Whittlesea Amcal', country:'Australia',postcode:'3757',street_address:'69 Church St  Whittlesea VIC 3757')
Stockist.create(name:'Whitsunday Pharmacy', country:'Australia',postcode:'4802',street_address:'Sh 11 Whitsundays Shopping Centre Shute Harbour Rd. CANNONVALE. QLD 4802')
Stockist.create(name:'Whitebridge Phamacy', country:'Australia',postcode:'2290',street_address:'136 Dudley Rd, Whitebridge NSW 2290')
Stockist.create(name:'West Street Hideaway', country:'Australia',postcode:'4350',street_address:'196 West St SOUTH TOOWOOMBA, QLD, 4350')
Stockist.create(name:'Watsonia Pharmacy', country:'Australia',postcode:'3087',street_address:'45 Watsonia Rd, Watsonia, VIC 3087')
Stockist.create(name:'Wangara Pharmacy', country:'Australia',postcode:'6065',street_address:'9/2 Prindiville Dr  Wangara WA 6065')
Stockist.create(name:'Wallis C &amp; Son', country:'Australia',postcode:'3142',street_address:'426 Toorak Rd  Toorak VIC 3142')
Stockist.create(name:'Vital Beauty ', country:'Australia',postcode:'4152',street_address:'Shop 7/3 Mayfield Rd Carina, QLD, 4152')
Stockist.create(name:'Verve Beauty Therapy', country:'Australia',postcode:'3101',street_address:'4/4-14 Walpole St  Kew VIC 3101')
Stockist.create(name:'Versailles Beauty', country:'Australia',postcode:'4301',street_address:'1 / 4 Jirra Street  ')
Stockist.create(name:'UpBeet Health and Wholefoods Wonthaggi', country:'Australia',postcode:'3995',street_address:'125 Graham St, Wonthaggi VIC 3995')
Stockist.create(name:'Ultra Essence Skin &amp; Body', country:'Australia',postcode:'4740',street_address:'15 Blacks Beach Rd  Blacks Beach QLD 4740')
Stockist.create(name:'Ultimate Indulgence Beauty Therapy', country:'Australia',postcode:'3814',street_address:'Shop 1, 91 Main Street, Garfield, VIC 3814')
Stockist.create(name:'A Glamorous Touch', country:'Australia',postcode:'2322',street_address:'5 Avard Close')
Stockist.create(name:'A Kur Day Spa', country:'Australia',postcode:'2227',street_address:'17 Casuarina Rd')
Stockist.create(name:'Allura Hairdressing Boutique', country:'Australia',postcode:'3806',street_address:'10 Wheeler Street')
Stockist.create(name:'Ann Hassarati Makeup', country:'Australia',postcode:'2153',street_address:'36 Rockley Avenue')
Stockist.create(name:'Ara Beauty', country:'Australia',postcode:'2011',street_address:'Se 810 2-14 Kings Cross Rd')
Stockist.create(name:'B Gorgeous', country:'Australia',postcode:'2540',street_address:'Shop 3 / 1 Tallyan Point Rd')
Stockist.create(name:'Beauty By Georgie Cullen', country:'Australia',postcode:'3806',street_address:'36 Coolong Ave')
Stockist.create(name:'Beauty Presence', country:'Australia',postcode:'2602',street_address:'Unit 4/2 Montford ST,')
Stockist.create(name:'Beauty with Michele', country:'Australia',postcode:'2031',street_address:'170 Clovelly Road')
Stockist.create(name:'Beautyfull', country:'Australia',postcode:'2047',street_address:'lv 1 20B 30-50 Lyons Rd')
Stockist.create(name:'Bella Vera True Beauty', country:'Australia',postcode:'2100',street_address:'33 Golden Grove')
Stockist.create(name:'Bellabox', country:'Australia',postcode:'3121',street_address:'Unit 6, 83-87 Dover Street')
Stockist.create(name:'Berry Beauty Escape', country:'Australia',postcode:'2535',street_address:'65 Queens Street')
Stockist.create(name:'Blush Cosmetics', country:'Australia',postcode:'2000',street_address:'Shop 909B World Square Shopping Centre')
Stockist.create(name:'Brow &amp; Beauty', country:'Australia',postcode:'2018',street_address:'Shop 1 62 Maloney St')
Stockist.create(name:'Catwalk Hair &amp; Beauty', country:'Australia',postcode:'2111',street_address:'230 Victoria Rd')
Stockist.create(name:'Classique Hair Design', country:'Australia',postcode:'2620',street_address:'180 Crawford street')
Stockist.create(name:'Clay Organic Beauty', country:'Australia',postcode:'2482',street_address:'97 Dalley Street')
Stockist.create(name:'Cosmetic Laser Clinic', country:'Australia',postcode:'2606',street_address:'Se 4 36-38 Corinna St')
Stockist.create(name:'Creative Beaute', country:'Australia',postcode:'2850',street_address:'17 Perry Street,')
Stockist.create(name:'Crystal Essenic', country:'Australia',postcode:'2259',street_address:'Po Box 592')
Stockist.create(name:'Dr Earth', country:'Australia',postcode:'2042',street_address:'287 - 289 King Street')
Stockist.create(name:'Elegance Beauty', country:'Australia',postcode:'2601',street_address:'Shop 19, Centre Point Plaza Petrie Plaza')
Stockist.create(name:'Elume Beauty Salon', country:'Australia',postcode:'2440',street_address:'13 Tozer Street')
Stockist.create(name:'Emmadean', country:'Australia',postcode:'2039',street_address:'Shop 2, 654 Darling Street ')
Stockist.create(name:'Empress Beauty Salon &amp; Day Spa', country:'Australia',postcode:'2790',street_address:'62 Main St')
Stockist.create(name:'EnhanSe Natural Wellbeing', country:'Australia',postcode:'2324',street_address:'17 Bangalay Close')
Stockist.create(name:'Essence of Eve', country:'Australia',postcode:'2539',street_address:'13 Buckland St')
Stockist.create(name:'FACIAL CO', country:'Australia',postcode:'4054',street_address:'65 Gilston Street')
Stockist.create(name:'Fancy Dish', country:'Australia',postcode:'2800',street_address:'109 Moulder Street')
Stockist.create(name:'Flannerys Benowa', country:'Australia',postcode:'4217',street_address:'Bronberg Plaza, Slatyer Avenue')
Stockist.create(name:'Flannerys Chermside', country:'Australia',postcode:'4032',street_address:'Corner Rode &amp; Webster Roads,')
Stockist.create(name:'Flannerys Loganholme', country:'Australia',postcode:'4129',street_address:'Shop 5/1 Bryants Rd')
Stockist.create(name:'Flannerys Maroochydore', country:'Australia',postcode:'4558',street_address:'Central One, 45 Plaza Pde')
Stockist.create(name:'Flannerys Miami', country:'Australia',postcode:'4220',street_address:'2184 Gold Coast Highway')
Stockist.create(name:'Flannerys Paradise Point', country:'Australia',postcode:'4216',street_address:'Shop 1A, 17 Grice Avenue')
Stockist.create(name:'Flannerys Robina', country:'Australia',postcode:'4218',street_address:'Shop 7 Easy T Centre Cnr Scottsdale Drive &amp; Christine Avenue')
Stockist.create(name:'Flannerys Taringa', country:'Australia',postcode:'4068',street_address:'191 Moggill Road')
Stockist.create(name:'Fundies Wholefood Market Lismore', country:'Australia',postcode:'2480',street_address:'140 Keen Street')
Stockist.create(name:'The Green Dispensary ', country:'Australia',postcode:'5152',street_address:'28 Mount Barker Road')
Stockist.create(name:'Greenbank Pharmacy ', country:'Australia',postcode:'4124',street_address:'Corner Pub Lane, Teviot Road')
Stockist.create(name:'Hagley &amp; Osmond Pharmacy', country:'Australia',postcode:'2380',street_address:'204 Conadilly Street')
Stockist.create(name:'Halka B Organics', country:'Australia',postcode:'6160',street_address:'Shop 8, The Piazza, (Off South Terrace)')
Stockist.create(name:'Harpers Pharmacy Earlwood', country:'Australia',postcode:'2206',street_address:'6 Clarke Street')
Stockist.create(name:'Health &amp; Savings Harrington Park Pharmacy', country:'Australia',postcode:'2576',street_address:'Shop 4-5 Fairwater Drive, Harrington Park Plaza,')
Stockist.create(name:'Hastings Health Food &amp; Clinic ', country:'Australia',postcode:'3915',street_address:'46 High street ')
Stockist.create(name:'Hawthorn Road Nova Pharmacy ', country:'Australia',postcode:'3131',street_address:'490 Springvale Road')
Stockist.create(name:'Health Information Pharmacy  ', country:'Australia',postcode:'3023',street_address:'74 Neale Road')
Stockist.create(name:'Health Life ', country:'Australia',postcode:'6018',street_address:' Karrinyup Shopping Centre, Karrinyup Road')
Stockist.create(name:'Healthpoint Chemist Helensvale ', country:'Australia',postcode:'4212',street_address:'Shop 1037/38 Westfield Shopping Centre/1-29 Millaroo Drive ')
Stockist.create(name:'HealthSmart Pharmacy Melbourne', country:'Australia',postcode:'3052',street_address:'Shop, 5 Grattan Street ')
Stockist.create(name:'Healthpoint Day &amp; Night', country:'Australia',postcode:'4740',street_address:' 65 Sydney Street')
Stockist.create(name:'Heavens Beauty Salon', country:'Australia',postcode:'6153',street_address:'2/38 Moolyeen Road')
Stockist.create(name:'Hibiscus Beauty', country:'Australia',postcode:'3114',street_address:'Shop 1 &amp; 2 1 Hopetoun Rd')
Stockist.create(name:'Hip Pharmacy Brimbank ', country:'Australia',postcode:'3023',street_address:'28 Neale Road')
Stockist.create(name:'Hollywood Pharmacy', country:'Australia',postcode:'6009',street_address:'29 Hampden Road')
Stockist.create(name:'Hope Island Amcal Chempro Chemist', country:'Australia',postcode:'4212',street_address:'Santa Barbara Road, Shop 9-11 Hope Island Shopping Centre')
Stockist.create(name:'Elite Body Treatments', country:'Australia',postcode:'3079',street_address:'2/242 Lower Heidelberg Road')
Stockist.create(name:'iBeauty Skin &amp; Nail Care', country:'Australia',postcode:'3088',street_address:'69 Grimshaw Street')
Stockist.create(name:'Impressions In Highton', country:'Australia',postcode:'3216',street_address:'4 Bellevue Ave')
Stockist.create(name:'Hair &amp; Beauty by Irene Evans', country:'Australia',postcode:'3940',street_address:'3/52 Grenville Grove')
Stockist.create(name:'Ishtar Beauty', country:'Australia',postcode:'3215',street_address:' 27 Milton Street')
Stockist.create(name:'J adore Lashes ', country:'Australia',postcode:'3806',street_address:'5 Kruger Street')
Stockist.create(name:'JC Unique Health &amp; Beauty', country:'Australia',postcode:'3131',street_address:'295 Springfield Road')
Stockist.create(name:'Jieya', country:'Australia',postcode:'3175',street_address:'76 Langhorne Street')
Stockist.create(name:'Jon Ravechs Prescription Shoppe', country:'Australia',postcode:'3058',street_address:'11-17 Orvieto Street')
Stockist.create(name:'Karen Carter Chemist', country:'Australia',postcode:'2380',street_address:'270/274 Conadilly Street')
Stockist.create(name:'Khodarys Pharmacy', country:'Australia',postcode:'2357',street_address:'77 John Street ')
Stockist.create(name:'La Tua Bellezza ', country:'Australia',postcode:'3109',street_address:' 28 Meryl Street')
Stockist.create(name:'Le Dee Makeover', country:'Australia',postcode:'3630',street_address:'14B Tower Arcade 222 Maude Street')
Stockist.create(name:'Makeup and Glow ', country:'Australia',postcode:'4064',street_address:'Suite 13/261 Given Terrace')
Stockist.create(name:'Makeup For You ', country:'Australia',postcode:'7250',street_address:'6 David Street')
Stockist.create(name:'McKenzies Chemist', country:'Australia',postcode:'6050',street_address:'689 Beaufort Street')
Stockist.create(name:'Mega Health Mitcham', country:'Australia',postcode:'5062',street_address:'Shop 48, Mitcham Sq Shopping Centre')
Stockist.create(name:'Mega Save Chemist', country:'Australia',postcode:'2250',street_address:'620-658 Terrigal Drive')
Stockist.create(name:'Mega Save Pharmacy', country:'Australia',postcode:'2290',street_address:'Charlestown Square, Pearson Street ')
Stockist.create(name:'Melton Pharmacy', country:'Australia',postcode:'3337',street_address:'2/211 Barries Road')
Stockist.create(name:'Mermaids', country:'Australia',postcode:'3226',street_address:' 3/85 The Parade')
Stockist.create(name:'Meticulous Beauty', country:'Australia',postcode:'3181',street_address:'1/182 Commercial Road')
Stockist.create(name:'Midland Gate Shopping Centre', country:'Australia',postcode:'6056',street_address:'274 Great Eastern Highway')
Stockist.create(name:'Millewa Spa Retreat', country:'Australia',postcode:'3564',street_address:'509-511 High Street')
Stockist.create(name:'Miss Eyelash', country:'Australia',postcode:'3930',street_address:'25 Ranelagh Drive')
Stockist.create(name:'Miss Eyelash', country:'Australia',postcode:'3184',street_address:'Upstairs 1 Ormond Road')
Stockist.create(name:'Glamazon Hair Studio', country:'Australia',postcode:'835',street_address:'Shop 6 452 Stuart Hwy Coolalinga Village')
Stockist.create(name:'Glow Beauty Therapy', country:'Australia',postcode:'2430',street_address:'Cnr Of Albert St And Pulteney St')
Stockist.create(name:'Go Vita  Ballina Fair', country:'Australia',postcode:'2478',street_address:'Shop 65 Ballina Fair Kerr Street')
Stockist.create(name:'Go Vita Byron Bay', country:'Australia',postcode:'2481',street_address:'Shop 2 / 69 Jonson Street')
Stockist.create(name:'Go Vita Cairns City', country:'Australia',postcode:'4870',street_address:'48 Aplin street')
Stockist.create(name:'Go Vita Cessnock', country:'Australia',postcode:'2325',street_address:'Shop 18 Cessnock Plaza, Keene &amp; Cooper Streets')
Stockist.create(name:'Go Vita Chermside', country:'Australia',postcode:'4032',street_address:'Shop 126 Westfield Chermside, Gympie Road')
Stockist.create(name:'Go Vita Coffs Central', country:'Australia',postcode:'2450',street_address:'Ground Floor Coffs Central  Harbour Drive')
Stockist.create(name:'Go Vita Earlvillie', country:'Australia',postcode:'4870',street_address:'Shop 126 Stockland Earlville Mulgrave Road')
Stockist.create(name:'Go Vita Edgecliff', country:'Australia',postcode:'2027',street_address:'Shop 6 East Point Food Fair')
Stockist.create(name:'Go Vita Hervey Bay', country:'Australia',postcode:'4655',street_address:'Shop 7 Urangan Central Shopping Centre')
Stockist.create(name:'Go Vita Katoomba', country:'Australia',postcode:'2780',street_address:'Shop 3B Katoomba Fair Parke Street')
Stockist.create(name:'Go Vita Kurrajong', country:'Australia',postcode:'2758',street_address:'Shop 1147 Grosevale rd')
Stockist.create(name:'Go Vita Lane Cove', country:'Australia',postcode:'2066',street_address:'15A Burns Bay Road')
Stockist.create(name:'Go Vita Loganholme', country:'Australia',postcode:'4129',street_address:'Shop 64B Hyperdome Shopping Centre')
Stockist.create(name:'Go Vita Narellan', country:'Australia',postcode:'2567',street_address:' 326 Camden Valley Way')
Stockist.create(name:'Go Vita Newport Beach', country:'Australia',postcode:'2106',street_address:'2/355 Barrenjoey Road')
Stockist.create(name:'Go Vita Nowra', country:'Australia',postcode:'2541',street_address:'27 Kinghorn Street')
Stockist.create(name:'Go Vita Salamander Bay', country:'Australia',postcode:'2317',street_address:'Shop 11 Salamander Bay Shopping Centre')
Stockist.create(name:'Go Vita The Junction', country:'Australia',postcode:'2291',street_address:'179 Union Street')
Stockist.create(name:'Go Vita Toowoomba', country:'Australia',postcode:'4350',street_address:'139 Herries Street')
Stockist.create(name:'Go Vita Tweed City', country:'Australia',postcode:'2486',street_address:'Shop 100 Tweed City Shopping Centre Minjungbal Street')
Stockist.create(name:'Go Vita West End', country:'Australia',postcode:'4101',street_address:'Shop 14 West End Markets 69/79 Boundary Street')
Stockist.create(name:'Hair and Beauty on Goonoo Goonoo Tania', country:'Australia',postcode:'2340',street_address:'229 Goonoo Goonoo Rd,')
Stockist.create(name:'Hanna\'s Beauty', country:'Australia',postcode:'2541',street_address:'10 Coral Sea Drive')
Stockist.create(name:'Happy Herb Shop', country:'Australia',postcode:'2300',street_address:'97 Hunter Street')
Stockist.create(name:'Healthy Life Buderim', country:'Australia',postcode:'4556',street_address:'Shop 1 56 Burnett Street')
Stockist.create(name:'Healthy Life Cardiff', country:'Australia',postcode:'2285',street_address:'Shop T9 Woolworths Cardiff Crn Macquarie &amp; Mains Rd')
Stockist.create(name:'Healthy Life Dubbo', country:'Australia',postcode:'2830',street_address:'269 Darling Street')
Stockist.create(name:'Huxley School of Make up', country:'Australia',postcode:'4220',street_address:'1/91 West Burleigh Rd')
Stockist.create(name:'Indulgence at Kurmond', country:'Australia',postcode:'2757',street_address:'Shop 3, 519 Bells Line of Road')
Stockist.create(name:'Ingenue  skin &amp; Massage', country:'Australia',postcode:'2538',street_address:'3/97 Princes HWY')
Stockist.create(name:'Isis Day Spa', country:'Australia',postcode:'2539',street_address:'1 Commonwealth Avenue')
Stockist.create(name:'Jess\'s Hair and Makeup', country:'Australia',postcode:'2148',street_address:'83 Stephen St')
Stockist.create(name:'Jessica Jane - Paramedical &amp; Natural Beauty Therapy', country:'Australia',postcode:'2830',street_address:'Suite 3/88-90 Macquarie Street')
Stockist.create(name:'Pure Beauty by Angie Beauty and Hair ', country:'Australia',postcode:'2525',street_address:'Westfield Shoppingtown Shop 45 Princes Hwy')
Stockist.create(name:'Le Body Beaute', country:'Australia',postcode:'2216',street_address:'Shop 2, 251-269 Bay Street')
Stockist.create(name:'LIPSTICK REPUBLIC', country:'Australia',postcode:'3195',street_address:'PO BOX 7011')
Stockist.create(name:'LYNS SKIN CLINIC', country:'Australia',postcode:'2530',street_address:'36 Baan Baan Street')
Stockist.create(name:'Madame Butterfly', country:'Australia',postcode:'2481',street_address:'Shop 11 Feros Arcade')
Stockist.create(name:'Magic Mountain Health Foods', country:'Australia',postcode:'2484',street_address:'Shop 4 10-16 Brisbane Street')
Stockist.create(name:'Mink Hair &amp; Beauty', country:'Australia',postcode:'2650',street_address:'69 Coleman Steet')
Stockist.create(name:'Mr Vitamin Go Vita', country:'Australia',postcode:'2067',street_address:'324 Victoria Ave')
Stockist.create(name:'Muswellbrook Nail And Beauty', country:'Australia',postcode:'2333',street_address:'1460 Giants Creek Road')
Stockist.create(name:'Natural Beauty Skin Clinic', country:'Australia',postcode:'2641',street_address:'Suite 2-334 Griffith Road')
Stockist.create(name:'Natural Body Image', country:'Australia',postcode:'2620',street_address:'Shop16 Karabar Shopping Centre')
Stockist.create(name:'Natural Food Store', country:'Australia',postcode:'4556',street_address:'330 Mons Rd')
Stockist.create(name:'Naturally Radiant', country:'Australia',postcode:'4224',street_address:'PO box 238')
Stockist.create(name:'Pharmacy Express Mt Annan', country:'Australia',postcode:'2567',street_address:'1 Main Street')
Stockist.create(name:'Meadow Heights Pharmacy', country:'Australia',postcode:'3048',street_address:'Shop 5 Meadow Heights Shopping Centre Paringa Boulevard')
Stockist.create(name:'Highlands Pharmacy Select', country:'Australia',postcode:'3064',street_address:'Shop 9, Stockland Highlands 300 Grand Boulevard')
Stockist.create(name:'Pharmacy Select', country:'Australia',postcode:'3082',street_address:'G 65, 415 McDonalds Road')
Stockist.create(name:'Lyndarum Pharmacy Select', country:'Australia',postcode:'3076',street_address:'Shop T-7 Epping North Shopping Centre 2 Lyndarum Drive')
Stockist.create(name:'Pharmacy World Fawkner', country:'Australia',postcode:'3060',street_address:'63/65 Bonwick Street')
Stockist.create(name:'Berwick Pharmacy', country:'Australia',postcode:'3806',street_address:'51 High Street')
Stockist.create(name:'PharmaSave Pharmacy - Brentford', country:'Australia',postcode:'3131',street_address:'4-6 Brentford Square ')
Stockist.create(name:'Pharmasave Charman Road Pharmacy', country:'Australia',postcode:'3192',street_address:'322 Charman Road')
Stockist.create(name:'Pharmasave Mountain Gate Pharmacy', country:'Australia',postcode:'3156',street_address:'29 Mountain Gate Shopping Centre')
Stockist.create(name:'Pharmasave Pharmacy Northcote', country:'Australia',postcode:'3070',street_address:'Shop 5, 3 Separation Street')
Stockist.create(name:'Plaza Pharmacy Bass Hill', country:'Australia',postcode:'2197',street_address:'753 Hume Highway ')
Stockist.create(name:'Pro-health', country:'Australia',postcode:'3095',street_address:'Shop 21, 906 Main Road')
Stockist.create(name:'Amcal Pharmacy Waurn Ponds', country:'Australia',postcode:'3216',street_address:'1d/173-199 Pioneer Road')
Stockist.create(name:'Pulse Pharmacy', country:'Australia',postcode:'3152',street_address:'Shop 1060, Knox Shopping Centre. Corner Stud Road &amp; Burwood Highway')
Stockist.create(name:'Ramai Skin and Body Care', country:'Australia',postcode:'3442',street_address:'6 Corinella Road')
Stockist.create(name:'Raymond\'s Pharmacy Kempsey', country:'Australia',postcode:'2440',street_address:'24 Smith Street')
Stockist.create(name:'Restore Beauty &amp; Skin Clinic', country:'Australia',postcode:'3147',street_address:'287 High Street')
Stockist.create(name:'Rita Abi Khalil - Lebanese Belly Dancer', country:'Australia',postcode:'3073',street_address:' rita.a.khalil@gmail.com')
Stockist.create(name:'Soul Pattinson Chemist', country:'Australia',postcode:'4230',street_address:' Robina Town Centre, Arbour Lane')
Stockist.create(name:'Romeo\'s Organic Wholefoods', country:'Australia',postcode:'5006',street_address:'71-79 O\'Connell Street')
Stockist.create(name:'Ron Davis Pharmacy', country:'Australia',postcode:'3337',street_address:' 308-312 High Street')
Stockist.create(name:'Rowville Lakes Pharmacy', country:'Australia',postcode:'3178',street_address:' 2/150 Kelletts Road')
Stockist.create(name:'Sadleirs Pharmacy', country:'Australia',postcode:'4850',street_address:'1 Lannercost Street')
Stockist.create(name:'Salamander Amcal Pharmacy', country:'Australia',postcode:'2317',street_address:' Salamander Shopng Centre')
Stockist.create(name:'SCHMINK Beauty House', country:'Australia',postcode:'3018',street_address:'90 Railway Street')
Stockist.create(name:'Scone Chemist', country:'Australia',postcode:'2337',street_address:'153 Kelly Street')
Stockist.create(name:'Naturally Safe', country:'Australia',postcode:'3168',street_address:'71 Manton Road')
Stockist.create(name:'Scott-Dibben Chemist', country:'Australia',postcode:'2289',street_address:'Shop 1060 Westfield')
Stockist.create(name:'Chemmart Pharmacy', country:'Australia',postcode:'3198',street_address:'115A Nepean Highway')
Stockist.create(name:'Nerinasbellezza Face and Body Studio', country:'Australia',postcode:'2092',street_address:'Shop 18 567 Sydney Rd')
Stockist.create(name:'Shades Hair Studio', country:'Australia',postcode:'7010',street_address:'285 Main Road')
Stockist.create(name:'Sharkra Health &amp; Beauty', country:'Australia',postcode:'7000',street_address:'110 Collins Street')
Stockist.create(name:'Nimbin Emporium', country:'Australia',postcode:'2480',street_address:'58 Cullen St')
Stockist.create(name:'Noreen\'s Beauty Studio', country:'Australia',postcode:'2830',street_address:'Shop 1, 46 Victoria St')
Stockist.create(name:'Shop Neutral', country:'Australia',postcode:'3181',street_address:'Shop 6 Prahran Market 163 Commercial Road')
Stockist.create(name:'North Nowra Beauty', country:'Australia',postcode:'2541',street_address:'Shop 15 North Nowra Shopping Centre')
Stockist.create(name:'Skinfit Body &amp; Beauty', country:'Australia',postcode:'3280',street_address:'150 Timor Street')
Stockist.create(name:'Scynergy Medispa', country:'Australia',postcode:'6023',street_address:'16b/50 Marri Road')
Stockist.create(name:'Soler Nails ', country:'Australia',postcode:'3032',street_address:'41 Fisher Parade')
Stockist.create(name:'One Room Salon', country:'Australia',postcode:'2024',street_address:'Shop1 414 Bronte Road ')
Stockist.create(name:'Solley Lew\'s Pharmacy', country:'Australia',postcode:'3182',street_address:'39-41 Fitzroy Street')
Stockist.create(name:'Organic Bliss Meleny', country:'Australia',postcode:'4552',street_address:'11 Coral St')
Stockist.create(name:'Raw Organic Australia, Brisbane  -', country:'Australia',postcode:'4020',street_address:'realfoodraw@live.com.au')
Stockist.create(name:'Soul Pattinson Chemist', country:'Australia',postcode:'2770',street_address:' Westfield Mt Druitt, 21 Luxford Road')
Stockist.create(name:'Pure Bliss', country:'Australia',postcode:'2794',street_address:'83 Kendal Street')
Stockist.create(name:'Spoilt Beauty Boutique', country:'Australia',postcode:'3094',street_address:' 26 Were Street')
Stockist.create(name:'Rafael At Cosmo', country:'Australia',postcode:'2028',street_address:'G11 2/22 Knox Street')
Stockist.create(name:'Spraytan Queen', country:'Australia',postcode:'3108',street_address:'134 Ayr Street')
Stockist.create(name:'St Helena Amcal Pharmacy', country:'Australia',postcode:'3089',street_address:'Shop 3, St Helena Market Place, Aqueduct Road')
Stockist.create(name:'Star Skin Body Beauty', country:'Australia',postcode:'4218',street_address:'Level 2, 17 Lavarack Road')
Stockist.create(name:'Stud Park Amcal ', country:'Australia',postcode:'3178',street_address:'Shop 36 Stud Park Shopping Centre')
Stockist.create(name:'Revive with Jo', country:'Australia',postcode:'2534',street_address:'29 Saxonia Road')
Stockist.create(name:'Rouche Boutique', country:'Australia',postcode:'2170',street_address:'9/153-155 Nuwarra Rd')
Stockist.create(name:'Studio Village Pharmacy', country:'Australia',postcode:'4210',street_address:'Studio Drive')
Stockist.create(name:'Styles On South', country:'Australia',postcode:'3690',street_address:'25 South Street')
Stockist.create(name:'Sally Richardson Make Up', country:'Australia',postcode:'3205',street_address:'337 Clarendon St')
Stockist.create(name:'Salus Spa &amp; Beauty', country:'Australia',postcode:'2095',street_address:'Suite 18, 74-78 The Corso')
Stockist.create(name:'Caxton Lane Amcal Pharmacy', country:'Australia',postcode:'4000',street_address:'Shop 16 61 Petrie Terrace')
Stockist.create(name:'Sasha\'s Hair', country:'Australia',postcode:'2026',street_address:'215 Bondi Rd')
Stockist.create(name:'Express Discount Pharmacy Logan Hyperdome', country:'Australia',postcode:'4129',street_address:'Shop 1-2 Logan Hyperdome, Corner Pacific Highway &amp; Bryants Road')
Stockist.create(name:'Friendlies Chemists Subiaco', country:'Australia',postcode:'6008',street_address:'136-142 Rokeby Road')
Stockist.create(name:'Scruples Hair &amp; Beauty', country:'Australia',postcode:'2541',street_address:'SHOP 8A 45-53 KINGHORNE STREET')
Stockist.create(name:'Skin Essence', country:'Australia',postcode:'2602',street_address:'33/193 Mouat Street')
Stockist.create(name:'Good Life Health Stores', country:'Australia',postcode:'6069',street_address:'Shop T8 The shops')
Stockist.create(name:'Skin Perfection Boutique', country:'Australia',postcode:'2118',street_address:'Shop 3, 14-20 Carmen Drive')
Stockist.create(name:'Skin Plus', country:'Australia',postcode:'2073',street_address:'95 Grandview Street,')
Stockist.create(name:'St George Pharmacy', country:'Australia',postcode:'4487',street_address:'103 Victoria Street')
Stockist.create(name:'Skinwear Pty Ltd trading as Beauty Me', country:'Australia',postcode:'2159',street_address:'PO Box 404')
Stockist.create(name:'Smithfield Go-Vita', country:'Australia',postcode:'4878',street_address:'Shop 151 Smithfield Centre Captain Cook Hwy ')
Stockist.create(name:'Spa Veda', country:'Australia',postcode:'2478',street_address:'66 Ballina st')
Stockist.create(name:'Stacey\'s Secret Beauty Salon', country:'Australia',postcode:'2097',street_address:'Shop 4D 65 Veterans Parade')
Stockist.create(name:'Superstyle', country:'Australia',postcode:'2607',street_address:'Shop 2 South Lands Shopping Centre 2/ 22 Mawson Pl, ')
Stockist.create(name:'The Beauty Bar', country:'Australia',postcode:'2483',street_address:'3/32 Mullumbimbi St')
Stockist.create(name:'Tina Kays Beauty', country:'Australia',postcode:'2320',street_address:'52 Sempill Street')
Stockist.create(name:'Total Bliss Body Spa', country:'Australia',postcode:'2500',street_address:'114 Kembla Street')
Stockist.create(name:'Totally Fab', country:'Australia',postcode:'2285',street_address:'191B Main Rd')
Stockist.create(name:'Wellbeing Women', country:'Australia',postcode:'2777',street_address:'95 Burns Rd')
Stockist.create(name:'Wild Rose Organics', country:'Australia',postcode:'2621',street_address:'2/38 ELLENDON ST,')
Stockist.create(name:'xternalbeauty', country:'Australia',postcode:'4054',street_address:'4 Chatswood Crt')
Stockist.create(name:'Brallis AB', country:'Sweden',postcode:'SE904 22',street_address:'Norre Obbola Vagen 89')
Stockist.create(name:'Cocktail Cosmetics Ltd', country:'United Kingdom',postcode:'B75',street_address:'Vision Point - Suite 21A, Vaughan Trading Estate Sedgley Rd East')
Stockist.create(name:'Crave Beauty', country:'United States',postcode:'48439',street_address:'9186 Meadowland Drive')
Stockist.create(name:'Eyecon Bahamas', country:'United States',postcode:'20191',street_address:'11961 Barrel Cooper Ct')
Stockist.create(name:'Glamourbox', country:'Philippines',postcode:'1600',street_address:'16 Malipajo St.')
Stockist.create(name:'Inside Out Beauty Bar', country:'United States',postcode:'11710',street_address:'2789 Merrick Road')
Stockist.create(name:'Make up by Rory', country:'United States',postcode:'33137',street_address:'2001 Biscayne Blvd 117/77')
Stockist.create(name:'ROOTS the Beauty Underground', country:'United States',postcode:'92651',street_address:'384 Forest Ave. #9')
Stockist.create(name:'Soul Patterson Hoppers Crossing', country:'Australia',postcode:'3029',street_address:'Shop 3, 24-48 Old Geelong Rd')
Stockist.create(name:'Pharmacy Select Roxburgh', country:'Australia',postcode:'3064',street_address:'Shop 2 Roxburgh Park Shopping Centre Cnr David Munroe Drive &amp; Somerton Road')
Stockist.create(name:'Terry White Annandale', country:'Australia',postcode:'4814',street_address:'Shop 1 Annandale Central Shopng Cntr, Cnr University Rd &amp; MacArthur Drive')
Stockist.create(name:'Ralphs Pharmacy', country:'Australia',postcode:'2560',street_address:'246 Queen St')
Stockist.create(name:'Vaucluse Pharmacy', country:'Australia',postcode:'2030',street_address:'93 New South Head Rd  ')
Stockist.create(name:'Pharmacy Select Wyndham', country:'Australia',postcode:'3029',street_address:'Shp 5, Wyndham Village Shpg Cntr Cnr Sayers &amp; Morris Rds ')
Stockist.create(name:'Optimal Pharmacy Plus Carine', country:'Australia',postcode:'6023',street_address:'5/ 485 Beach Rd')
Stockist.create(name:'Stay Healthy', country:'Australia',postcode:'6062',street_address:'Shop 41 Galleria Morley, Russell St')
Stockist.create(name:'Ocean Reef Pharmacy', country:'Australia',postcode:'6027',street_address:'Cnr Marina Blvd &amp; Venturi Drv ')
Stockist.create(name:'Go Vita Southern Cross', country:'Australia',postcode:'3008',street_address:'Level 1, CS 11 Southern Cross Station  99 Spencer St ')
Stockist.create(name:'Derwent Park Pharmacy', country:'Australia',postcode:'7009',street_address:'254 Main Rd')
Stockist.create(name:'Terry White Yarrawonga', country:'Australia',postcode:'3730',street_address:'54 Belmore St')
Stockist.create(name:'Terry White  Cairns Central', country:'Australia',postcode:'4870',street_address:'Cairns Central 1 - 21 McLeod St, ')
Stockist.create(name:'Chemplus Newton', country:'Australia',postcode:'5074',street_address:'Shop 6&amp;7 Central Shopping Centre ,CNR Gorge &amp; Newton Rds')
Stockist.create(name:'Beaufort St 24 Hour Chemist', country:'Australia',postcode:'6050',street_address:'647 Beaufort St')
Stockist.create(name:'Go Vita Ballarat', country:'Australia',postcode:'3350',street_address:'7 Sturt St')
Stockist.create(name:'Stay Healthy Subiaco', country:'Australia',postcode:'6008',street_address:'Shop 26 Crossways Shopping Centre Rokeby Rd')
Stockist.create(name:'My Healthy Place Floreat', country:'Australia',postcode:'6014',street_address:'Shop 71a Howtree Way')
Stockist.create(name:'Denmark Pharmacy', country:'Australia',postcode:'6333',street_address:'20 Strickland St')
Stockist.create(name:'Curtis Adams Chemmart', country:'Australia',postcode:'3572',street_address:'46 Reid St')
Stockist.create(name:'Go Vita Mt Barker', country:'Australia',postcode:'5251',street_address:'Cental Mall Shop 9, McLaren St ')
Stockist.create(name:'Prahran Health Food', country:'Australia',postcode:'3181',street_address:'201 Commercial Road')
Stockist.create(name:'Ibuki Health', country:'Australia',postcode:'4567',street_address:'71/6 Quamby Place')
Stockist.create(name:'De La Rue', country:'Australia',postcode:'3931',street_address:'Shop 13 90 Main St')
Stockist.create(name:'Healthy Life Kawana', country:'Australia',postcode:'4575',street_address:'Shop 348 Kawana Shopping World Nicklin Way')
Stockist.create(name:'Beauty by Danielle', country:'Australia',postcode:'2500',street_address:'34 Atchison Street')
Stockist.create(name:'Burnside Village Chemmart', country:'Australia',postcode:'5065',street_address:'Shop 111, 447 Portrush Rd')
Stockist.create(name:'Beaconsfield Community Phy', country:'Australia',postcode:'6163',street_address:'Shop 15 Winterfold S/C 115 Lefroy Rd')
Stockist.create(name:'Brows &amp; Lash Corner', country:'Australia',postcode:'3141',street_address:'Shop 4, 430-436 Chapel St')
Stockist.create(name:'Go Vita Fairview Park', country:'Australia',postcode:'5126',street_address:'Shop 8, 325 Hancock Rd')
Stockist.create(name:'Health Kick Whitfords', country:'Australia',postcode:'6025',street_address:'Shop 234 Whitford City S/C Whitfords Ave')
Stockist.create(name:'Chemcoast Airlie Beach D&amp;N Phyarmacy', country:'Australia',postcode:'4802',street_address:'366 Shute Harbour Rd')
Stockist.create(name:'Discount Drug Store - Aitkenvale', country:'Australia',postcode:'4814',street_address:'268 Ross River Rd')
Stockist.create(name:'Victoria Melissas Pharmacy', country:'Australia',postcode:'3168',street_address:'Shop 1/1310 Centre Rd')
Stockist.create(name:'Fountain of Youth ', country:'Australia',postcode:'4051',street_address:'126 Banks Street')
Stockist.create(name:'Reflections Day Spa  ', country:'Australia',postcode:'3016',street_address:'143 Railway Place')
Stockist.create(name:'Kingscliffe Beauty &amp; Massage', country:'Australia',postcode:'2487',street_address:'11/60 Marine Parade')
Stockist.create(name:'Red Rose Beauty', country:'Australia',postcode:'2171',street_address:'117 Carmichael Drive')
Stockist.create(name:'Go Vita Maryborough', country:'Australia',postcode:'4650',street_address:'Shop 2, 239 Adelaide Street')
Stockist.create(name:'Heavenlee', country:'Australia',postcode:'4211',street_address:'45 Renfrew Drive')
Stockist.create(name:'Beauty Worx', country:'Australia',postcode:'2650',street_address:'4/56 Forsyth Street ')
Stockist.create(name:'At Home Beauty Therapy', country:'Australia',postcode:'4171',street_address:'7/77 Bilyana Street')
Stockist.create(name:'Indulge Beauty Bar', country:'Australia',postcode:'2902',street_address:'Shop 2-3 Carleton Street')
Stockist.create(name:'Renew Skin &amp; Body Clinic', country:'Australia',postcode:'2571',street_address:'161a Argyle Street')
Stockist.create(name:'Bresilienne Wax Lounge', country:'Australia',postcode:'2640',street_address:'Shop 8, 586 Dean Street')
Stockist.create(name:'Belle Femme', country:'Australia',postcode:'2099',street_address:'42 Nimbey Avenue')
Stockist.create(name:'Capalaba Park Amcal Max', country:'Australia',postcode:'4157',street_address:'64-45 Redland Bay Rd')
Stockist.create(name:'Deep Cleanse', country:'Australia',postcode:'3228',street_address:'Shop 5, 15 Bell St,')
Stockist.create(name:'Euroa Pharmacy', country:'Australia',postcode:'3666',street_address:'26 Binney St')
Stockist.create(name:'IMAGE ONE BEAUTY', country:'Australia',postcode:'6111',street_address:'33 Buchanan Road')
Stockist.create(name:'Karen Martiensen', country:'Afghanistan',postcode:'4218',street_address:'24 Petrel Ave,')
Stockist.create(name:'Manly West Chammart Pharmacy', country:'Australia',postcode:'4179',street_address:'S10 Crn Manly &amp; Hargreaves Roads')
Stockist.create(name:'Mornington Amcal', country:'Australia',postcode:'3931',street_address:'113 Main St')
Stockist.create(name:'Mosman Drive in Chemist', country:'Australia',postcode:'6012',street_address:'590 Stirling Hwy, ')
Stockist.create(name:'Mount Evelyn Pharmacy', country:'Australia',postcode:'3796',street_address:'35 Wray Crescent')
Stockist.create(name:'Mt Barker Pharmacy', country:'Australia',postcode:'6324',street_address:'23 Lowood Road')
Stockist.create(name:'Mt Isa Pharmacy', country:'Australia',postcode:'4825',street_address:'Shop 1/80 Camooweal Street')
Stockist.create(name:'Myrtleford Pharmacy', country:'Australia',postcode:'3737',street_address:'43 Clyde St')
Stockist.create(name:'Narrabri Pharmacy', country:'Australia',postcode:'2390',street_address:'127 Maitland St')
Stockist.create(name:'Natasha Skin &amp; Body', country:'Australia',postcode:'3006',street_address:'Shop 14 89 City Road ')
Stockist.create(name:'Neutral Bay Pharmacy', country:'Australia',postcode:'2089',street_address:'177 Military Rd ')
Stockist.create(name:'Nicole\'s Angelic Beauty Therapy', country:'Australia',postcode:'3630',street_address:'13 Chevrolet Ave ')
Stockist.create(name:'Nightingales Pharmacy Erskine ', country:'Australia',postcode:'6210',street_address:'Shop 4 / Erskine Central Shopping Centre, Old Coast Road, ')
Stockist.create(name:'Nightingales Pharmacy Kalamanda ', country:'Australia',postcode:'6076',street_address:'123 canning Rd, ')
Stockist.create(name:'Noosa holistic Health', country:'Australia',postcode:'4566',street_address:'35 Mary Street ')
Stockist.create(name:'North Brighton Pharmacy ', country:'Australia',postcode:'3186',street_address:'326 Bay Street ')
Stockist.create(name:'Ogg\'s Pharmacy', country:'Australia',postcode:'3141',street_address:'189 Toorak Road')
Stockist.create(name:'Olga Hardy Beauty Therapy', country:'Australia',postcode:'3044',street_address:'3 Elgin Street')
Stockist.create(name:'Om Day Spa', country:'Australia',postcode:'6282',street_address:'3/40 Hemsley Road')
Stockist.create(name:'Organic Salon Dimentions', country:'Australia',postcode:'2084',street_address:'6/19 Yulong Avenue ')
Stockist.create(name:'Oria Massa Holistic Centre', country:'Australia',postcode:'3070',street_address:'579 High Street ')
Stockist.create(name:'Our Corner Pharmacy', country:'Australia',postcode:'3216',street_address:'145 High St ')
Stockist.create(name:'Outshine', country:'Australia',postcode:'4006',street_address:'Shop 3 Centro on James 39 James St ')
Stockist.create(name:'Paloma ', country:'Australia',postcode:'3550',street_address:'461 Hargreaves st ')
Stockist.create(name:'Pamper Clinic', country:'Australia',postcode:'3220',street_address:'313 Packington St ')
Stockist.create(name:'Paradise Point Pharmacy', country:'Australia',postcode:'4216',street_address:'30 The Esplanade ')
Stockist.create(name:'Pardeys Belmont Village Pharmacies', country:'Australia',postcode:'3216',street_address:'10/ 65 High St')
Stockist.create(name:'Perry Moshidis Pharmacy', country:'Australia',postcode:'3121',street_address:'22/246 Church St, ')
Stockist.create(name:'Pharmacy360 Stotts Corner', country:'Australia',postcode:'3122',street_address:'Cnr Riversdale &amp; Glenferrie Roads')
Stockist.create(name:'Quality Pharmacy Knox', country:'Australia',postcode:'3152',street_address:'Shop 1060, Knox S/C. Cnr Stud Rd &amp; Burwood Hwy, ')
Stockist.create(name:'Seaford Pharmacy', country:'Australia',postcode:'3198',street_address:'115 Nepean Hwy ')
Stockist.create(name:'Seeds of Wellness', country:'Australia',postcode:'2680',street_address:'Shop16, Griffin Plaza, Corner Crossing &amp; Yambil Sts')
Stockist.create(name:'Karisma Hair Studio', country:'Australia',postcode:'5031',street_address:'Shop 2 158 Henley Beach Rd ')
Stockist.create(name:'Style with Cindy', country:'Australia',postcode:'3148',street_address:'Suite 1,Level 2 Boarder Tower')
Stockist.create(name:'Sunshine Plaza Pharmacy', country:'Australia',postcode:'3020',street_address:'Sunshine Plaza S/C, Shop 38-39 Hampshire Rd, ')
Stockist.create(name:'Super Saver Sunshine', country:'Australia',postcode:'3020',street_address:'Shop 45 Sunshine Market Place ')
Stockist.create(name:'Surfers Paradise Midnight', country:'Australia',postcode:'4217',street_address:'Shop 36, 3221 Surfers Paradise Boulevard ')
Stockist.create(name:'Swan Hill Beauty Salon', country:'Australia',postcode:'3585',street_address:'261 Campbell Street')
Stockist.create(name:'Swansea Guardian', country:'Australia',postcode:'2281',street_address:'148 Pacific Hwy 	')
Stockist.create(name:'Terry White Mermaid Waters', country:'Australia',postcode:'4218',street_address:'Shop C28, Q Super Centre, Cnr Bermuda &amp; Markeri Streets ')
Stockist.create(name:'Terry White Albury', country:'Australia',postcode:'2640',street_address:'543 Dean St ')
Stockist.create(name:'Terry White Clifford Gardens Toowoomba', country:'Australia',postcode:'4350',street_address:'S47 Clifford Gardens S/C  cnr James St &amp; Anzac Ave')
Stockist.create(name:'Terry White Hamilton', country:'Australia',postcode:'2292',street_address:'119-125 Beaumont St ')
Stockist.create(name:'Terry White Mitchelton', country:'Australia',postcode:'4053',street_address:'Shop 86 Brookside S/centre, 159 Osborne Rd,')
Stockist.create(name:'Terry White Myer Centre', country:'Australia',postcode:'4000',street_address:'Shop 103, Myer Centre Level E, 91 Queen St ')
Stockist.create(name:'Terry White Pharmacy Gladstone Park ', country:'Australia',postcode:'3043',street_address:'Shop 104, Gladstone Park Shopping Centre/Gladstone Park Dr, ')
Stockist.create(name:'Terry White Pharmacy Sunbury', country:'Australia',postcode:'3429',street_address:' 83/85 Evans Arcade, ')
Stockist.create(name:'Terry White Wodonga', country:'Australia',postcode:'3690',street_address:'127 High St, ')
Stockist.create(name:'Terry White Chemists Carindale Upper', country:'Australia',postcode:'4152',street_address:'Shop 2069 Westfield S/centre,  Cnr Creek &amp; Old Cleveland Roads')
Stockist.create(name:'Terry White Garden City', country:'Australia',postcode:'4122',street_address:' Shop 2084. Garden City Shopping Centre, Cnr Kessels &amp; Logan Roads ')
Stockist.create(name:'Terry White Taigum', country:'Australia',postcode:'4018',street_address:'Cnr Church &amp; Beams Road ')
Stockist.create(name:'The Berry Pharmacy', country:'Australia',postcode:'2535',street_address:'113 Queen St')
Stockist.create(name:'Chai Color Me Hairdressing', country:'Australia',postcode:'3041',street_address:'295 Buckley Street')
Stockist.create(name:'The Essence Of A Woman', country:'Australia',postcode:'3101',street_address:'323 High Street ')
Stockist.create(name:'The Greater Discount', country:'Australia',postcode:'3047',street_address:'1/11-17 Pearcedale Parade ')
Stockist.create(name:'The Green Disp Blackwood', country:'Australia',postcode:'5051',street_address:'202 Main Rd ')
Stockist.create(name:'The Green Disp Erindale', country:'Australia',postcode:'5068',street_address:'361A Kensington Rd ')
Stockist.create(name:'The Hair Lounge', country:'Australia',postcode:'7250',street_address:'Level 1 125A Brisbane Street ')
Stockist.create(name:'The Whole Body', country:'Australia',postcode:'3820',street_address:'Shop 1 /126 Albert rd ')
Stockist.create(name:'Thomas &amp; Chong', country:'Australia',postcode:'3450',street_address:'2 FREDERICK STREET')
Stockist.create(name:'Tropical Beauty', country:'Australia',postcode:'4870',street_address:'19 Brady Close ')
Stockist.create(name:'Tuncurry', country:'Australia',postcode:'2428',street_address:'70 Manning St, ')
Stockist.create(name:'You Save Chemist Avalon', country:'Australia',postcode:'2107',street_address:'60 Old Barrenjoey Rd ')
Stockist.create(name:'Sabastian Salons ', country:'Australia',postcode:'2000',street_address:'Lv 9 117 Macquarie Street ')
Stockist.create(name:'Catwalk Hair &amp; Beauty Paramatta ', country:'Australia',postcode:'2150',street_address:'Shop 5048 Westfield Shopping Centre, Level 5. 159-175 Church Street ')
Stockist.create(name:'Surfcoast Wholefoods', country:'Australia',postcode:'3228',street_address:'Shop 104, 41 Bristol Road')
Stockist.create(name:'Aunt Maggies Balaclava', country:'Australia',postcode:'3183',street_address:'270 Carlise Street')
Stockist.create(name:'Aunt Maggies Malvern', country:'Australia',postcode:'3144',street_address:'72 Glenferrie Road')
Stockist.create(name:'Flannerys Wynnum', country:'Australia',postcode:'4178',street_address:'Shop B1 &amp; B2, 20-21 Wynnum Road, Wynnum Plaza')
Stockist.create(name:'Makeup by Angela Paris', country:'Australia',postcode:'5033',street_address:'8 Dover Street')
Stockist.create(name:'Edgewater Town Mall', country:'Australia',postcode:'2285',street_address:'Shop 5, 720 Main Rd')
Stockist.create(name:'Priceline Firle', country:'Australia',postcode:'5070',street_address:'Shop 4 Glynburn Plaza 151 Glynburn Rd')
Stockist.create(name:'Pacific Pines Amcal Chempro', country:'Australia',postcode:'4210',street_address:'Shop 2, 14 Studio Drive')
Stockist.create(name:'Aphrodites on the Lake', country:'Australia',postcode:'2280',street_address:'Shop 4/28 Allambee Place')
Stockist.create(name:'Beauty By Tasha', country:'Australia',postcode:'2640',street_address:'108 Rivergum Drive')
Stockist.create(name:'Livelife Pharmacy  ', country:'Australia',postcode:'2481',street_address:'31 Jonson Street')
Stockist.create(name:'My Healthy Place Karrinyup', country:'Australia',postcode:'6018',street_address:'Shop F36 Karrinyup Shopping Centre Karrinyup Rd')
Stockist.create(name:'Skynergy', country:'Australia',postcode:'6023',street_address:'16b/50 Marri Road')
Stockist.create(name:'Goodlife Ellenbrooke', country:'Australia',postcode:'6069',street_address:'Shop T42 ‰ÛÏThe Shops‰Û Main st,')
Stockist.create(name:'777 Whitford‰Ûªs City Pharmacy', country:'Australia',postcode:'6025',street_address:'Shop 42, Westfield Whitford City, Whitfords Avenue')
Stockist.create(name:'Chemmart Fountains Pharmacy ', country:'Australia',postcode:'6530',street_address:'113 Marine Terrace')
Stockist.create(name:'Optimal Carine Pharmacy Plus', country:'Australia',postcode:'6023',street_address:'S5/473 Beach Road')
Stockist.create(name:'Forestlakes Pharmacy', country:'Australia',postcode:'6108',street_address:'Shopping Centre, Corner Forest Lakes Drive &amp; Murdoch Road')
Stockist.create(name:'Thomsons Lake Pharmacy', country:'Australia',postcode:'6164',street_address:'1/850 North Lake Road')
Stockist.create(name:'Blossoms Health Food Store', country:'Australia',postcode:'6233',street_address:'Shop 24 Treendale Shopping Centre, The Promendade')
Stockist.create(name:'Miami Health Solutions', country:'Australia',postcode:'6210',street_address:'Shop 2 Erskine Shopping Centre, Cnr Old Coast Rd &amp; Oakleigh Dr')
Stockist.create(name:'Terry White Coorparoo ', country:'Australia',postcode:'4151',street_address:'332 Old Cleveland Road ')
Stockist.create(name:'Logan Central Plaza Pharmacy ', country:'Australia',postcode:'4114',street_address:'Logan Central Shopping Plaza (K-mart Plaza) 38-74 Wembley Road ')
Stockist.create(name:'Natures Emporium', country:'Australia',postcode:'4670',street_address:'55 Bourbong Street')
Stockist.create(name:'Hibiscus Health Market', country:'Australia',postcode:'2448',street_address:'Shop 7 Nambucca Plaza A1, ')
Stockist.create(name:'Terry White - Indooroopilly', country:'Australia',postcode:'4068',street_address:'Shop 1019, 322 Moggill Road')
Stockist.create(name:'Healthpoint Chemist The Pines', country:'Australia',postcode:'4221',street_address:'Shop 22, Pines Shopping Centre')
Stockist.create(name:'Healthpoint Chemist - Tweed Heads', country:'Australia',postcode:'2486',street_address:'Shop 115, Tweed City S/Centre , Minjumgbal Street')
Stockist.create(name:'Sadleirs Pharmacy - Ingham', country:'Australia',postcode:'4850',street_address:'1 Lannercost Street')
Stockist.create(name:'Terry White - Mermaid Waters', country:'Australia',postcode:'4218',street_address:'Shop C28, Q Super Centre - Cnr Bermuda &amp; Markeri Sts')
Stockist.create(name:'Pardeys Eastbrooke Medical Centre Pharmacy', country:'Australia',postcode:'3216',street_address:' 75 -77 Roslyn Rd')
Stockist.create(name:'Terry White - Rockhampton', country:'Australia',postcode:'4701',street_address:'Shop 91B, Stockland S/C, Cnr Yamba Rd &amp; Bruce Hwy')
Stockist.create(name:'Go Vita Boronia Park', country:'Australia',postcode:'2111',street_address:'99 Pittwater Road')
Stockist.create(name:'Maple Street Co-Op', country:'Australia',postcode:'4552',street_address:'37 Maple St')
Stockist.create(name:'Rustic Hair Room', country:'Australia',postcode:'3218',street_address:'Shop 3,226 Pakington Street')
Stockist.create(name:'The Goddess Beauty', country:'Australia',postcode:'2076',street_address:'Se 2 5 Redleaf Ave')
Stockist.create(name:'The Nail Depot', country:'Australia',postcode:'6008',street_address:'Village Close Shop 9, 1 Forrest St')
Stockist.create(name:'Ooh La Lana', country:'Australia',postcode:'7322',street_address:'63 Simpson Street')
Stockist.create(name:'Advanced Aesthethics Australia', country:'Australia',postcode:'3023',street_address:'9/242-244 Caroline Springs Bvd')
Stockist.create(name:'Nails Talk &amp; Beauty', country:'Australia',postcode:'3192',street_address:'Unit 1 4 Coleman Crt')
Stockist.create(name:'Lila Hair Design', country:'Australia',postcode:'3012',street_address:'273 Geelong Rd')
Stockist.create(name:'Egolista', country:'Australia',postcode:'2810',street_address:'40 Main Street')
Stockist.create(name:'ARGUS', country:'Hong Kong SAR China',postcode:'HONG KONG',street_address:'HONG KONG')
Stockist.create(name:'Glamour and Beauty', country:'Australia',postcode:'3046',street_address:'101 Wheatsheaf Rd')
Stockist.create(name:'Aunt Maggies Fitzroy ', country:'Australia',postcode:'3065',street_address:'188-196 Gertrude Street')
Stockist.create(name:'Arundel Amcal Pharmacy - Chempro', country:'Australia',postcode:'4214',street_address:'Shop 6, Arundel Plaza, 230-232 Napper Road')
Stockist.create(name:'Barcaldine Pharmacy ', country:'Australia',postcode:'4725',street_address:'91 Oak Street')
Stockist.create(name:'Beerwah Soul Pattinson Chemist', country:'Australia',postcode:'4519',street_address:'Shop 8, Beerwah Market Place, 54 Simpson Street')
Stockist.create(name:'Broadbeach Amcal Chempro Chemist', country:'Australia',postcode:'4218',street_address:'Oracle Building, Shop 1E / 13 Charles Avenue')
Stockist.create(name:'Chemcoast - Airlie Beach Day &amp; Night Pharmacy', country:'Australia',postcode:'4802',street_address:'366 Shute Harbour Road')
Stockist.create(name:'Chemist Outlet - Townsville', country:'Australia',postcode:'4814',street_address:'Domain Central, 5 / 143 Duckworth Street')
Stockist.create(name:'Dicky Beach Pharmacy', country:'Australia',postcode:'4551',street_address:'Shop 5-6 Beerburrum Street')
Stockist.create(name:'Discount Drug Store - Pease St', country:'Australia',postcode:'4870',street_address:'Shop 22, 159 - 161 Pease St, Piccone\'s S/Village')
Stockist.create(name:'Discount Drug Store - Newmarket', country:'Australia',postcode:'4051',street_address:'Shop 106/107, Reading Newmarket, 400 Newmarket Road')
Stockist.create(name:'Duggans Amcal Pharmacy', country:'Australia',postcode:'4370',street_address:'Shop 10, Rose City S/World, Palmerin Street')
Stockist.create(name:'Dupuys Amcal - North Mackay', country:'Australia',postcode:'4740',street_address:'12-14 Grandview Drive, Greenfields')
Stockist.create(name:'Infinity Beauty Spa', country:'Australia',postcode:'3620',street_address:'32 Unitt street')
Stockist.create(name:'LiveLife Pharmacy - Byron Bay Plaza', country:'Australia',postcode:'2481',street_address:'Shop 4B, 5&amp;6, Byron Bay Plaza North, Jonson Street')
Stockist.create(name:'Logan Central Plaza Pharmacy', country:'Australia',postcode:'4114',street_address:'Logan Central S/Plaza (Kmart Plaza), 38 - 74 Wembley Rd')
Stockist.create(name:'Lucy Walker Chemmart Pharmacy', country:'Australia',postcode:'4390',street_address:'95 Marshall Street')
Stockist.create(name:'Mt. Isa Pharmacy First', country:'Australia',postcode:'4825',street_address:'Shop 1, 80 Camooweal Street')
Stockist.create(name:'Range Pharmacy', country:'Australia',postcode:'4350',street_address:'11A James Street')
Stockist.create(name:'Robina Easy-T Centre Amcal Pharmacy', country:'Australia',postcode:'4226',street_address:'Shop 15, Robina Easy-T Centre, Cnr Scottsdale Rd &amp; Christine Ave')
Stockist.create(name:'Robina Soul Pattinson Chemist', country:'Australia',postcode:'4226',street_address:'Shop AD.4 58 / 56 Robina Town Centre')
Stockist.create(name:'Sadleirs Pharmacy - Ingham', country:'Australia',postcode:'4850',street_address:'1 Lannercost Street')
Stockist.create(name:'Springfield Day &amp; Night Amcal Chemist', country:'Australia',postcode:'4300',street_address:'Springfield Fair S/C, Cnr Springfield Parkway &amp; Topaz Rd')
Stockist.create(name:'Surfers Paradise Midnight Amcal Chemist', country:'Australia',postcode:'4217',street_address:'Shop 36, 3221 Surfers Paradise Boulevard')
Stockist.create(name:'Terry White - Annandale', country:'Australia',postcode:'4814',street_address:'Shop 1, Annandale S/C, Cnr University Rd &amp; McArthur Dr')
Stockist.create(name:'Terry White - Brookside Centre', country:'Australia',postcode:'4053',street_address:'Shop 86 ,Brookside Shopping Centre, 159 Osborne Road')
Stockist.create(name:'Terry White - Cairns Central', country:'Australia',postcode:'4870',street_address:'Shop 112, Cairns Central S/Ctr,  Cnr Aplin &amp; McLeod Sts')
Stockist.create(name:'Terry White - Carindale Upper', country:'Australia',postcode:'4152',street_address:'Shop 2069, Westfield S/Town, Cnr Creek &amp; Old Cleveland')
Stockist.create(name:'Terry White - Carindale Lower', country:'Australia',postcode:'4152',street_address:'Shop 1112, Westfield S/Town, Creek &amp; Old Cleveland')
Stockist.create(name:'Terry White - Chermside', country:'Australia',postcode:'4032',street_address:'Shop 334/36 Westfield Chermside, Corner Gympie &amp; Hamilton Roads')
Stockist.create(name:'Terry White - Clifford Gardens Toowoomba', country:'Australia',postcode:'4350',street_address:'Shop 47, Clifford Gardens S/C, Cnr James St &amp; Anzac Ave')
Stockist.create(name:'Terry White - Clifton Beach', country:'Australia',postcode:'4879',street_address:'Shop 14, Captain Cook Hwy, Clifton Village S/Centre')
Stockist.create(name:'Terry White - Garden City', country:'Australia',postcode:'4122',street_address:'Shop 2084, Garden City S/C, Cnr Logan &amp; Kessels Rd')
Stockist.create(name:'Pharaohs Treasure', country:'United States',postcode:'FL',street_address:'2723 Timberlake Ave')
Stockist.create(name:'Go Vita Tenterfield', country:'Australia',postcode:'2372',street_address:'230 Rouse Street')
Stockist.create(name:'Grub Organics', country:'Australia',postcode:'4564',street_address:'20c Timari St')
Stockist.create(name:'Natural Food Market Neutral Bay', country:'Australia',postcode:'2089',street_address:'184 Military Rd')
Stockist.create(name:'Stay Healthy Morley', country:'Australia',postcode:'6062',street_address:'Shop 41, Galleria Shopping Centre, Russell Street')
Stockist.create(name:'Health Kick Rockingham', country:'Australia',postcode:'6068',street_address:'Shop G081 Rockingham City S/C, 1 Council Ave')
Stockist.create(name:'Health Kick Joondalup', country:'Australia',postcode:'6127',street_address:'Shop T101, Lakeside Joondalup S/C')
Stockist.create(name:'Healthy Choice Carousel', country:'Australia',postcode:'6107',street_address:'Shop T1101 Carousel S/Ctr, Albany Highway')
Stockist.create(name:'Stay Healthy Belmont', country:'Australia',postcode:'6104',street_address:'Belmont Forum S/C, Abernethy Road')
Stockist.create(name:'Goodlife Warwick', country:'Australia',postcode:'6024',street_address:'Shop 4 Centrol Warwick S/C, Beach Road')
Stockist.create(name:'Stay Healthy Landsadale', country:'Australia',postcode:'6055',street_address:'Shop 11, Kingsway City Sh/Ctr, Cnr Wanneroo/Hepburn Ave')
Stockist.create(name:'Stay Healthy Warnbro', country:'Australia',postcode:'6169',street_address:'Shop 36 Warnbro Fair S/C, Warnbro Sound Avenue')
Stockist.create(name:'Health Kick Raine Square', country:'Australia',postcode:'6000',street_address:'Shop 10 TM Raine Square, 306 Murray Street')
Stockist.create(name:'Healthy Choice Armadale', country:'Australia',postcode:'6112',street_address:'Shop 77, Armadale Shopping Centre, 224 Jull Street')
Stockist.create(name:'Geegelup General Supplies', country:'Australia',postcode:'6255',street_address:'130 Hampton Street')
Stockist.create(name:'Tumut Pharmacy', country:'Australia',postcode:'2720',street_address:'69 Wynyard St')
Stockist.create(name:'Callaghans Campus Pharmacy', country:'Australia',postcode:'2308',street_address:'Shop 110b/ 130 University Drv')
Stockist.create(name:'Terry White Chemist - Clifton Beach', country:'Australia',postcode:'4879',street_address:'Shop 14 Captain Cook Hwy, Clifton Village S/Centre')
Stockist.create(name:'Pharmasave Inverloch', country:'Australia',postcode:'3996',street_address:'1/12 A\'Beckett St')
Stockist.create(name:'North Fitzroy Pharmacy', country:'Australia',postcode:'3068',street_address:'35 Best St')
Stockist.create(name:'The Greater Discount Chemist', country:'Australia',postcode:'3020',street_address:'Shop 12/254 Hampshire Rd')
Stockist.create(name:'Leighton Beach Drive-In Pharmacy', country:'Australia',postcode:'6159',street_address:'108 Stirling Hwy')
Stockist.create(name:'Subiaco 7 Day Pharmacy', country:'Australia',postcode:'6008',street_address:'157-159 Rockeby Rd')
Stockist.create(name:'Aitkenvale Discount Drugstore', country:'Australia',postcode:'4814',street_address:'268 Ross River Road')
Stockist.create(name:'BJ\'s Pharmacy', country:'Australia',postcode:'7310',street_address:'56-58 Rooke Street Mall')
Stockist.create(name:'Style &amp; Grace', country:'Australia',postcode:'3170',street_address:'46 Monash Drive')
Stockist.create(name:'GMD Store', country:'Australia',postcode:'2287',street_address:'7/161 Maryland Drive')
Stockist.create(name:'Go Vita Ashfield', country:'Australia',postcode:'2131',street_address:'Shop 10, Ashfield Mall 260A Liverpool Rd')
Stockist.create(name:'Go Vita Hornsby', country:'Australia',postcode:'2077',street_address:'Shop 10, 25-29 Hunter St')
Stockist.create(name:'Go Vita Manly', country:'Australia',postcode:'2095',street_address:'Shop 11 The Corso')
Stockist.create(name:'Lunatic Fringe ', country:'Australia',postcode:'4011',street_address:'458 Sandgate Road')
Stockist.create(name:'Ilona on Broadbent Hair Skin Body ', country:'Australia',postcode:'820',street_address:'36 Broadbent Street ')
Stockist.create(name:'Hair by Amanda Hill', country:'Australia',postcode:'2421',street_address:'10 Rennie Street ')
Stockist.create(name:'Go Vita Corinda', country:'Australia',postcode:'4075',street_address:'Shop 5/661 Oxley Road')
Stockist.create(name:'Believe Hair &amp; Body', country:'Australia',postcode:'5118',street_address:'1A Bridge Street')
Stockist.create(name:'You Save Chemist Brookvale', country:'Australia',postcode:'2100',street_address:'Shop 422 Warringh Mall, Coles Dock ')
Stockist.create(name:'Rhys Jones Pharmacy', country:'Australia',postcode:'7018',street_address:'13 Bayfield Street')
Stockist.create(name:'Coventry Pharmacy', country:'Australia',postcode:'7307',street_address:'45A Gilbert St')
Stockist.create(name:'Commercial Rd Pharmacy', country:'Australia',postcode:'3181',street_address:'Shop 1, 212 Commercial Rd')
Stockist.create(name:'Victoria Parade Pharmacy', country:'Australia',postcode:'3065',street_address:'55 Victoria Parade')
Stockist.create(name:'Nova Collins Place Pharmacy', country:'Australia',postcode:'3000',street_address:'Shop 59-60 / 45 Collins Place')
Stockist.create(name:'Plunkets Pharmacy - Port Macquarie', country:'Australia',postcode:'2444',street_address:'158 Gordon St')
Stockist.create(name:'Kerrie Birch Styling', country:'Australia',postcode:'3189',street_address:'38 Royena Rd')
Stockist.create(name:'Chi Hair Skin Body - Glenelg', country:'Australia',postcode:'5045',street_address:'Shop 3 Lights Landing Marina Pier - Chappel Drive')
Stockist.create(name:'Organic Salon Dimentions Seaforth', country:'Australia',postcode:'2092',street_address:'6 Brook Road')
Stockist.create(name:'Hairyard', country:'Australia',postcode:'4226',street_address:'7 Heatherton Street')
Stockist.create(name:'Stylz 2 Go', country:'Australia',postcode:'4205',street_address:'Shop 3 Bethania Water Shopping Centre 78 Station Rd')
Stockist.create(name:'Applebom Beauty, Hair &amp; Wellbeing', country:'Australia',postcode:'4350',street_address:'22 James St')
Stockist.create(name:'Terry White Lutwyche', country:'Australia',postcode:'4030',street_address:'543 Lutwyche Road')
Stockist.create(name:'Lush Cuts &amp; Beauty', country:'Australia',postcode:'4556',street_address:'39 Main St')
Stockist.create(name:'Blooms- Giffith ', country:'Australia',postcode:'2680',street_address:'222 Banna Ave')
Stockist.create(name:'Terry White - Lutwyche', country:'Australia',postcode:'4030',street_address:'16 Lutwyche City S/Centre, 543 Lutwyche Rd')
Stockist.create(name:'Go Vita Ballina Central', country:'Australia',postcode:'2478',street_address:'10-44 Pacific Highway')
Stockist.create(name:'Rivive Health Foods Margaret River', country:'Australia',postcode:'6285',street_address:'Shop 1, 120 Bussell Highway')
Stockist.create(name:'Anubis Dermal Clinic', country:'Australia',postcode:'6108',street_address:'50 Forest Crescent')
Stockist.create(name:'Miami Health Solutions Meadow Springs', country:'Australia',postcode:'6210',street_address:'Shop 4  Meadow Springs Shopping Centre')
Stockist.create(name:'Go Vita Cherrybrook', country:'Australia',postcode:'2126',street_address:'Shop 31 Cherrybrook Village S/Centre Shepherds Drive')
Stockist.create(name:'Ballarat Health Foods', country:'Australia',postcode:'3350',street_address:'405A Sturt St')
Stockist.create(name:'Go Vita Shellharbour', country:'Australia',postcode:'2529',street_address:'Unit 15/75 Cygnet Avenue, Cygnet Centre')
Stockist.create(name:'Go Vita Revesby', country:'Australia',postcode:'2212',street_address:'34 Selems Parade')
Stockist.create(name:'House of Wax and Beauty', country:'Australia',postcode:'2325',street_address:'7 Vincent Street')
Stockist.create(name:'One Floor Cosmetics ', country:'Australia',postcode:'4557',street_address:'Suite 4, Mountain Creek Medical Centre, Karawatha Drive ')
Stockist.create(name:'Art Hair Studio', country:'Australia',postcode:'3193',street_address:'353 Balcombe Road')
Stockist.create(name:'Miami Health Solutions - Eskine', country:'Australia',postcode:'6210',street_address:'Cnr Old Coast Rd &amp; Oakleigh Drive')
Stockist.create(name:'Miami Health Solutions - Eskine', country:'Australia',postcode:'6210',street_address:'Cnr Old Coast Rd &amp; Oakleigh Drive')
Stockist.create(name:'Body Beautiful Jindera', country:'Australia',postcode:'2642',street_address:'91 Urana Street')
Stockist.create(name:'Go Vita Toormina', country:'Australia',postcode:'2452',street_address:'3/11 Minorca place')
Stockist.create(name:'Amcal Chempro Chemist Eagleby', country:'Australia',postcode:'4207',street_address:'Shop 14 Eagleby Plaza, Riverhills Rd')
Stockist.create(name:'Malouf Pharmacy - Merthyr Village', country:'Australia',postcode:'4005',street_address:'Merthyr Village S/Centre, 95 Merthyr Rd')
Stockist.create(name:'Burleigh Town Amcal', country:'Australia',postcode:'4220',street_address:'Shop 5 Stocklands S/Centre')
Stockist.create(name:'Market Square Day &amp; Night Chemist', country:'Australia',postcode:'4109',street_address:'Shop 5 Market Square S/Centre, cnr Harris Rd &amp; McCullough St')
Stockist.create(name:'All Ceezens', country:'Australia',postcode:'4849',street_address:'Shop 5, Victoria Arcade')
Stockist.create(name:'La Vita Hair &amp; Beauty', country:'Australia',postcode:'2200',street_address:'shop 3, Appian Way Compass')
Stockist.create(name:'Le Beauty Affair', country:'Australia',postcode:'N/A',street_address:'www.lebeautyaffair.com.au ')
Stockist.create(name:'Bambu Beauty Lash &amp; Brow Bar', country:'Australia',postcode:'2154',street_address:'Shop 1A 7-13 Victoria Ave')
Stockist.create(name:'In Home Indulgence', country:'Australia',postcode:'N/A',street_address:'No Address - Mobile Business ')
Stockist.create(name:'The Silken DragonFly', country:'Australia',postcode:'3685',street_address:'113 Main Street')
Stockist.create(name:'Riana\'s Health &amp; Skin Care Clinic', country:'Australia',postcode:'2904',street_address:'111 Clive Steele Ave')
Stockist.create(name:'Vanessa\'s Nail Spot', country:'Australia',postcode:'2330',street_address:'48 Castlereagh St')
Stockist.create(name:'Lumieres De Paris', country:'Australia',postcode:'2192',street_address:'27 Waverley St')
Stockist.create(name:'Nuyu', country:'Australia',postcode:'2500',street_address:'8 Mangerton Rd')
Stockist.create(name:'Glow Beauty Therapy on Gilbert', country:'Australia',postcode:'3072',street_address:'19 Gilbert Road')
Stockist.create(name:'Glow Dermal Therapy', country:'Australia',postcode:'2641',street_address:'Dragonfly House, 529 Macauley Street')
Stockist.create(name:'Go Vita Ocean Keys', country:'Australia',postcode:'6030',street_address:'Shope 171A Ocean Keys S/Ctr  36 Ocean Keys Boulevard')
Stockist.create(name:'Goodlife Geraldton', country:'Australia',postcode:'6530',street_address:'Shop 8 Penny Lane')
Stockist.create(name:'Genesis Beauty Clinic', country:'Australia',postcode:'6065',street_address:'18 Terrigal Pass')
Stockist.create(name:'Louise May Laser &amp; Skin Clinic', country:'Australia',postcode:'5065',street_address:'300 Greenhill Road,')
Stockist.create(name:'Cosmedic Fusion', country:'Australia',postcode:'5000',street_address:'148 Hutt Street')
Stockist.create(name:'Beauty Savvy', country:'Australia',postcode:'3000',street_address:'http://www.beautysavvy.com.au/')
Stockist.create(name:'Cassie Turner Beauty &amp; Makeup', country:'Australia',postcode:'2535',street_address:'113 Scott Street')
Stockist.create(name:'Shuswap Health Foods', country:'Canada',postcode:'V1E-1T3',street_address:'Piccadilly Mall 115-1151 10th Ave SW')
Stockist.create(name:'Vivian Essential Beauty', country:'Australia',postcode:'3212',street_address:'4 Kanowna Place')
Stockist.create(name:'Eve Makeup Artistry', country:'Australia',postcode:'3102',street_address:'http://www.evemakeup.com.au/')
Stockist.create(name:'Glo Dermaclinical on Highett', country:'Australia',postcode:'3190',street_address:'Shop 2, 535 Highett Road')
Stockist.create(name:'Broome Natural Wellness', country:'Australia',postcode:'6725',street_address:'Shop 20 Broome Boulevard 106 Frederick Street')
Stockist.create(name:'Jieya Professional Beauty', country:'Australia',postcode:'3175',street_address:'76 Langhorne St')
Stockist.create(name:'Jieya Professional Beauty', country:'Australia',postcode:'3175',street_address:'76 Langhorne St')
Stockist.create(name:'Jieya Professional Beauty', country:'Australia',postcode:'3175',street_address:'76 Langhorne St')
Stockist.create(name:'Pro Health', country:'Australia',postcode:'3095',street_address:'Shop 21, Eltham Village Shopping Centre, Main Road')
Stockist.create(name:'Skinique', country:'Australia',postcode:'3011',street_address:'38-42 Byron St')
Stockist.create(name:'Style on South', country:'Australia',postcode:'3690',street_address:'Shop 6 25 South Street')
Stockist.create(name:'The House of Life Clinic', country:'Australia',postcode:'3143',street_address:'70 Armadale St')
Stockist.create(name:'Ivanhoe Health Store', country:'Australia',postcode:'3079',street_address:'96 Upper Heidelberg Road')
Stockist.create(name:'Kempsey Bulk Health Foods', country:'Australia',postcode:'2440',street_address:'30 Smith Street')
Stockist.create(name:'The Crystal Temple', country:'Australia',postcode:'2022',street_address:'50 Spring Street')
Stockist.create(name:'Sheshwarz Beauty', country:'Australia',postcode:'2196',street_address:'Shop G3 level 2 Centro Roselands Roselands Dr')
Stockist.create(name:'Naturally You', country:'Australia',postcode:'2903',street_address:'Shop 2 Sangster Place')
Stockist.create(name:'Green Horse', country:'Australia',postcode:'3070',street_address:'255 High Street')
Stockist.create(name:'Go Vita Raw Pantry', country:'Australia',postcode:'4122',street_address:'Shop 1350, Westfield Garden City, Logan Road')
Stockist.create(name:'Varuka Salon', country:'Australia',postcode:'3043',street_address:'191a  Melrose Drive')
Stockist.create(name:'Atone Lifestyle Salon', country:'Australia',postcode:'3051',street_address:'95 Errol Street')
Stockist.create(name:'Flannerys North Lakes', country:'Australia',postcode:'4509',street_address:'Shop 5B, 4-8 Burke Crescent,')
Stockist.create(name:'Manik The Hair Studio', country:'Australia',postcode:'2481',street_address:'Shop 3, Byrin Street')
Stockist.create(name:'Soul Skin &amp; Body WA', country:'Australia',postcode:'6728',street_address:'Unit 2, 9 Cassia Close')
Stockist.create(name:'Laser and Lipstick', country:'Australia',postcode:'2330',street_address:'Shop 3 1 Pitt Street')
Stockist.create(name:'Egyptian Bazaar', country:'Australia',postcode:'4217',street_address:'114 Paradise Centre')
Stockist.create(name:'Livelife Pharmacy Noosa', country:'Australia',postcode:'4567',street_address:'22 Sunshine Beach Rd, Noosa Junction ')
Stockist.create(name:'Amcal Cannonvale', country:'Australia',postcode:'4802',street_address:'Shop 15 Cantro S/Centre, 8 Galbraith Rd')
Stockist.create(name:'Discount Drug Store Mareeba', country:'Australia',postcode:'4872',street_address:'10 Raeleigh St')
Stockist.create(name:'Blooms The Chemist South West Rocks', country:'Australia',postcode:'2431',street_address:'Shop 9-10 The Rocks Shopping Fair')
Stockist.create(name:'Star Pharmacy', country:'Australia',postcode:'3101',street_address:'127 High St')
Stockist.create(name:'Pharmacy on Church', country:'Australia',postcode:'3122',street_address:'Suite 1a,  13-25 Church St')
Stockist.create(name:'Marlin Coast Amcal Chemist', country:'Australia',postcode:'4878',street_address:'Shop 1/2 Campus Shopping Village')
Stockist.create(name:'Castlemaine Health Food Store', country:'Australia',postcode:'3450',street_address:'107 Mostyn St')
Stockist.create(name:'Doll Face Makeup', country:'Australia',postcode:'2011',street_address:'Unit 4/16 St Neot Ave')
Stockist.create(name:'The Glamour Bar', country:'Australia',postcode:'4152',street_address:'2/107 Anzac Rd')
Stockist.create(name:'Fundies Paddington', country:'Australia',postcode:'4064',street_address:'219 Given Tce')
Stockist.create(name:'Healthshop Morayfield', country:'Australia',postcode:'4506',street_address:'Shop 99 Moray Shopping Centre 171 Morayfield Road')
Stockist.create(name:'Beauty Indulgence', country:'Australia',postcode:'2538',street_address:'94 Princess Hwy')
Stockist.create(name:'Spa Eleven', country:'Australia',postcode:'3550',street_address:'11 Forest Street')
Stockist.create(name:'Amcal Cannonvale ', country:'Australia',postcode:'4802',street_address:'Shop 15 Cantro S/Centre, 8 Galbraith Rd')
Stockist.create(name:'V Pharmacy Smithfield', country:'Australia',postcode:'4879',street_address:'Shop 121 Smithfield S/Centre, cnr Cook &amp; Kennedy Hwys')
Stockist.create(name:'Discount Drug Store Atherton', country:'Australia',postcode:'4883',street_address:'Shop 5A Silos S/Centre, Silos Rd')
Stockist.create(name:'Babinda Pharmacy', country:'Australia',postcode:'4861',street_address:'80 Munro St')
Stockist.create(name:'Yeppoon Chemmart', country:'Australia',postcode:'4703',street_address:'4 James St')
Stockist.create(name:'Torres Pharmacy', country:'Australia',postcode:'4860',street_address:'46 Edith St')
Stockist.create(name:'Malouf Pharmacy - Rockhampton', country:'Australia',postcode:'4701',street_address:'Northside Plaza S/Centre, 222-228 Musgrave St')
Stockist.create(name:'Carrum Downs Pharmacy', country:'Australia',postcode:'3201',street_address:'Shop 2 The local Village, 1095 Frankston/Dandenong Rd')
Stockist.create(name:'Auscare Yandina Pharmacy', country:'Australia',postcode:'4561',street_address:'5/18 Farrell St')
Stockist.create(name:'Swansea Pharmacy', country:'Australia',postcode:'7190',street_address:'28 franklin street')
Stockist.create(name:'Blooms - Woonona', country:'Australia',postcode:'2517',street_address:'399-401 Princes Highway')
Stockist.create(name:'Pharmasave - Moree', country:'Australia',postcode:'2400',street_address:'64 Balo St')
Stockist.create(name:'Plevey\'s Pharmacy', country:'Australia',postcode:'2550',street_address:'154 Carp St')
Stockist.create(name:'Terry White - Port Macquarie', country:'Australia',postcode:'2444',street_address:'Shop 47 Port Central S/Centre')
Stockist.create(name:'Blooms - Toormina', country:'Australia',postcode:'2452',street_address:'Shop N52 Centro S/Centre, Toormina Rd')
Stockist.create(name:'Narromine Pharmacy', country:'Australia',postcode:'2821',street_address:'53 Dandaloo st')
Stockist.create(name:'Health Focus Pharmacy Mudgee', country:'Australia',postcode:'2850',street_address:'Shop 2 84 Mortimer Street')
Stockist.create(name:'scount Drug Store - Kings Langley', country:'Australia',postcode:'2147',street_address:'Shop 5/125 James Cook Drive')
Stockist.create(name:'Blooms - Blacktown', country:'Australia',postcode:'2148',street_address:'Shop 1007 Ground Floor, Westpoint S/Centre')
Stockist.create(name:'Blaxland Day &amp; Night Pharmacy', country:'Australia',postcode:'2774',street_address:'138A Great Western Hwy')
Stockist.create(name:'Blooms Penrith - Nepean Square', country:'Australia',postcode:'2750',street_address:'Shop 39 Centro Nepean, Station St')
Stockist.create(name:'Best Buy Pharmacy', country:'Australia',postcode:'2800',street_address:'171 Lords Place')
Stockist.create(name:'Blooms - Tamworth', country:'Australia',postcode:'2340',street_address:'358 Peel St')
Stockist.create(name:'Bowral Guardian Chemist', country:'Australia',postcode:'2576',street_address:'306 Bong Bong St')
Stockist.create(name:'Blooms - Dubbo', country:'Australia',postcode:'2830',street_address:'Shop 15/16A Dubbo Square, Macquarie St')
Stockist.create(name:'Pokolbin Village Pharmacy', country:'Australia',postcode:'2320',street_address:'Shop 13,  Hunter Valley Gardens Village,  2090 Broke Road')
Stockist.create(name:'Erskineville Chemist', country:'Australia',postcode:'2043',street_address:'Shop 1,  83 Erskineville Road')
Stockist.create(name:'Blooms - Orange', country:'Australia',postcode:'2800',street_address:'Shop 19 Metro Plaza, 237 Summer St')
Stockist.create(name:'Amcal Max - Rutherford', country:'Australia',postcode:'2320',street_address:'Shop 6 East Mall Rutherford S/Centre')
Stockist.create(name:'DELROY CHEMMART PHARMACY', country:'Australia',postcode:'2830',street_address:'SHOP 15 WOOLWORTHS SHOPPING CENTRE')
Stockist.create(name:'Wamberal Pharmacist Advice', country:'Australia',postcode:'2260',street_address:'658 The Entrance Rd')
Stockist.create(name:'Blooms - Northbridge', country:'Australia',postcode:'2063',street_address:'Shop 13 Northbridge Plaza, Sailor Bay Rd')
Stockist.create(name:'Blooms - Penrith (Westfield Plaza)', country:'Australia',postcode:'2750',street_address:'Shop 110 Westfield Plaza')
Stockist.create(name:'Blooms - Erina', country:'Australia',postcode:'2250',street_address:'Shop T74 Karalta Road Erina Fair')
Stockist.create(name:'Terry White - Shoalhaven', country:'Australia',postcode:'2541',street_address:'Shop 12 Nowra Fair, East St')
Stockist.create(name:'Priceline Pharmacy - Renmark', country:'Australia',postcode:'5341',street_address:'10 Renmark Ave')
Stockist.create(name:'Centro Mildura Amcal Pharmacy', country:'Australia',postcode:'3500',street_address:'Shop MM1 Centro Mildura S/Centre, Deakin Ave')
Stockist.create(name:'City Markets Chemist', country:'Australia',postcode:'2600',street_address:'Shop EG01-02 Canberra Centre, Bunda St')
Stockist.create(name:'Inform Pharmacy - Thornleigh', country:'Australia',postcode:'2120',street_address:'57 Thornleigh Marketplace')
Stockist.create(name:'Blooms - Bathurst', country:'Australia',postcode:'2795',street_address:'Shop 18 Stockland Mall, William St')
Stockist.create(name:'Discount Day &amp; Night Pharmacy - Newtown', country:'Australia',postcode:'2042',street_address:'293 King St')
Stockist.create(name:'Blooms - Bathurst Shop 25 METRO', country:'Australia',postcode:'2795',street_address:'Shop 26 Bathurst Central S/Centre')
Stockist.create(name:'Healthpoint Pharmacy - Launceston', country:'Australia',postcode:'7250',street_address:'86A - 88 Johns St')
Stockist.create(name:'Blayney Pharmacy', country:'Australia',postcode:'2799',street_address:'112 Adelaide St')
Stockist.create(name:'Cremorne Town Centre Pharmacy', country:'Australia',postcode:'2090',street_address:'7 / 287 Military Rd,')
Stockist.create(name:'Amcal Max - Dapto', country:'Australia',postcode:'2530',street_address:'G120-121 Dapto Mall')
Stockist.create(name:'Blooms - Coogee', country:'Australia',postcode:'2034',street_address:'202-204 coogee Bay Rd')
Stockist.create(name:'The Molong Pharmacy', country:'Australia',postcode:'2866',street_address:'43-45 Bank ST')
Stockist.create(name:'Parkes Pharmacy', country:'Australia',postcode:'2870',street_address:'Shop 6 Metro Plaza, 279-283 Clarinda St')
Stockist.create(name:'Life Pharmacy - Forbes', country:'Australia',postcode:'2871',street_address:'Shop 3, 159-173 Lachlan St')
Stockist.create(name:'West Gosford Pharmacy', country:'Australia',postcode:'2250',street_address:'Shop 17 West Gosford S/Centre')
Stockist.create(name:'Darby Street Pharmacy', country:'Australia',postcode:'2300',street_address:'145 Darby Street')
Stockist.create(name:'Charnwood Capital Chemist', country:'Australia',postcode:'2615',street_address:'7-8 The Small Mall')
Stockist.create(name:'Blooms - Gordon', country:'Australia',postcode:'2072',street_address:'765 Pacific Hwy')
Stockist.create(name:'Soul Pattinson - Ermington', country:'Australia',postcode:'2115',street_address:'Shop 4, Betty Cuthbert Ave')
Stockist.create(name:'Amcal Max - Queanbeyan', country:'Australia',postcode:'2620',street_address:'23-25 Antill St')
Stockist.create(name:'Murry T Martin Pharmacy', country:'Australia',postcode:'5290',street_address:'23-25 Commercial St West')
Stockist.create(name:'McCarthy\'s Pharmacy - Orange', country:'Australia',postcode:'2800',street_address:'236 Summer St')
Stockist.create(name:'Terry White - Underwood', country:'Australia',postcode:'4119',street_address:'Shop 18/3215 Logan Rd')
Stockist.create(name:'Keperra Chemmart', country:'Australia',postcode:'4054',street_address:'Shop B Great Western S/Centre, cnr Samford &amp; Settlement Rds')
Stockist.create(name:'Family Pharmacy Granville', country:'Australia',postcode:'2142',street_address:'1/60 South St')
Stockist.create(name:'Eddie\'s Pharmacy Ramgate', country:'Australia',postcode:'2217',street_address:'211B Ramsgate Rd')
Stockist.create(name:'Manning River Pharmacy - Taree', country:'Australia',postcode:'2430',street_address:'191 Victoria St')
Stockist.create(name:'Birkenhead Amcal Chemist', country:'Australia',postcode:'2047',street_address:'Shop 136 Birkenhead Point, Roseby St')
Stockist.create(name:'Blooms - Lithgow', country:'Australia',postcode:'2790',street_address:'Shop 44-46 Lithgow S/Centre')
Stockist.create(name:'Urunga Amcal Pharmacy', country:'Australia',postcode:'2455',street_address:'10 Bowra St')
Stockist.create(name:'Discount Drug Store - Moree', country:'Australia',postcode:'2400',street_address:'Shop 2/215 Balo St')
Stockist.create(name:'Bondi Pharmacy', country:'Australia',postcode:'2026',street_address:'81 Hall St')
Stockist.create(name:'Pharmasave Eastgardens', country:'Australia',postcode:'2035',street_address:'Shop 157-159 Westfield, 152 Bunnerong Rd')
Stockist.create(name:'Blooms - Figtree', country:'Australia',postcode:'2525',street_address:'Shop 12-15 Westfield S/Town')
